use futures::future::Either;
use libp2p::kad::RecordKey;
pub use libp2p::pnet::PreSharedKey;
use libp2p::{
    autonat, core::upgrade::Version, dcutr, gossipsub, identify, identity::Keypair, kad, mdns,
    noise, pnet, relay, swarm::NetworkBehaviour, tcp, yamux, PeerId, Swarm, SwarmBuilder,
    Transport,
};

use std::error::Error;
use std::fs;
use std::path::Path;
use std::time::Duration;

use crate::base::config::{PhalanxConfig, PhalanxPhysics};
use crate::base::types::{PowerState, UnitInterval, VitalityRate};
use crate::primitives::identity::NetworkId;
use crate::security::gate::ForensicGate;

// --- CONSTANTS ---
pub type PhalanxKadStore = kad::store::MemoryStore;
pub const SERVICE_STORAGE: &[u8] = b"phalanx/service/storage/v1";
pub const STRONGHOLD_NAMESPACE: &[u8] = b"phalanx.stronghold.v1";

#[derive(Debug, thiserror::Error)]
pub enum DiscoveryError {
    #[error("Failed to serialize provider record")]
    SerializationError,
    #[error("DHT store is full or unavailable")]
    StorageError,
}

pub fn get_storage_key() -> RecordKey {
    RecordKey::new(&SERVICE_STORAGE)
}

/// The composite network behaviour struct for Phalanx.
#[derive(NetworkBehaviour)]
#[behaviour(out_event = "PhalanxEvent")]
pub struct PhalanxBehaviour {
    // ARCHITECTURAL FIX: First-class identity storage
    // The behaviour now knows "Self" without asking the Swarm.
    pub gossipsub: gossipsub::Behaviour,
    pub mdns: mdns::tokio::Behaviour,
    pub kademlia: kad::Behaviour<PhalanxKadStore>,
    pub identify: identify::Behaviour,
    pub relay_server: relay::Behaviour,
    pub relay_client: relay::client::Behaviour,
    pub dcutr: dcutr::Behaviour,
    pub autonat: autonat::Behaviour,
}

impl PhalanxBehaviour {
    /// Announces the local node as a Stronghold provider to the network.
    ///
    /// # Sentinel Argument
    /// The `local_node_id` must be passed explicitly. This ensures the
    /// forensic log is always signed by the caller's verified identity.
    pub fn announce_stronghold(&mut self, local_node_id: &NetworkId) -> Option<kad::QueryId> {
        let record_key = RecordKey::new(&STRONGHOLD_NAMESPACE);

        tracing::info!(
            target: "phalanx::transport",
            "Announcing local node as Stronghold provider"
        );

        self.kademlia
            .start_providing(record_key)
            .map_err(|_| DiscoveryError::StorageError)
            .ok_or_log(
                "dht_announce_fail",
                local_node_id,
                "DHT Announcement Failed",
            )
    }

    pub fn find_strongholds(&mut self) -> kad::QueryId {
        let record_key = RecordKey::new(&STRONGHOLD_NAMESPACE);

        tracing::info!(
            target: "phalanx::transport",
            "Initiating discovery for Stronghold providers"
        );

        self.kademlia.get_providers(record_key)
    }
}

/// Enumeration of all possible events generated by the `PhalanxBehaviour`.
#[derive(Debug)]
pub enum PhalanxEvent {
    Gossipsub(gossipsub::Event),
    Mdns(mdns::Event),
    Kademlia(kad::Event),
    Identify(Box<identify::Event>),
    RelayServer(relay::Event),
    RelayClient(relay::client::Event),
    Dcutr(dcutr::Event),
    Autonat(autonat::Event),
}

impl From<gossipsub::Event> for PhalanxEvent {
    fn from(v: gossipsub::Event) -> Self {
        Self::Gossipsub(v)
    }
}
impl From<mdns::Event> for PhalanxEvent {
    fn from(v: mdns::Event) -> Self {
        Self::Mdns(v)
    }
}
impl From<kad::Event> for PhalanxEvent {
    fn from(v: kad::Event) -> Self {
        Self::Kademlia(v)
    }
}
impl From<identify::Event> for PhalanxEvent {
    fn from(v: identify::Event) -> Self {
        Self::Identify(Box::new(v))
    }
}
impl From<relay::Event> for PhalanxEvent {
    fn from(v: relay::Event) -> Self {
        Self::RelayServer(v)
    }
}
impl From<relay::client::Event> for PhalanxEvent {
    fn from(v: relay::client::Event) -> Self {
        Self::RelayClient(v)
    }
}
impl From<dcutr::Event> for PhalanxEvent {
    fn from(v: dcutr::Event) -> Self {
        Self::Dcutr(v)
    }
}
impl From<autonat::Event> for PhalanxEvent {
    fn from(v: autonat::Event) -> Self {
        Self::Autonat(v)
    }
}

/// Constructs the foundational transport stack for the node.
///
/// This stack supports TCP and DNS, with optional PNet (Pre-Shared Key) encryption for private swarms.
/// It upgrades connections using Noise for security and Yamux for stream multiplexing.
///
/// # Arguments
/// * `local_key` - The node's identity keypair, used for Noise handshake.
/// * `psk` - Optional Pre-Shared Key. If provided, the transport is wrapped in a PNet layer.
///
/// # Returns
/// Returns a boxed transport that unifies the types of Encrypted (PNet) and Raw streams
/// into a single `Either` type, ensuring type consistency for the SwarmBuilder.
fn build_base_transport(
    local_key: &Keypair,
    psk: Option<PreSharedKey>,
) -> Result<
    libp2p::core::transport::Boxed<(PeerId, libp2p::core::muxing::StreamMuxerBox)>,
    Box<dyn Error>,
> {
    let noise_config = noise::Config::new(local_key)?;
    let yamux_config = yamux::Config::default();

    let base_transport = tcp::tokio::Transport::new(tcp::Config::default().nodelay(true));
    let dns_transport = libp2p::dns::tokio::Transport::system(base_transport)?;

    type RawStream = libp2p::tcp::tokio::TcpStream;
    type EncryptedStream = libp2p::pnet::PnetOutput<RawStream>;

    let transport = if let Some(key) = psk {
        let pnet_config = pnet::PnetConfig::new(key);
        dns_transport
            .and_then(move |socket, _| pnet_config.handshake(socket))
            .map(|stream, _| Either::<EncryptedStream, RawStream>::Left(stream))
            .upgrade(Version::V1)
            .authenticate(noise_config)
            .multiplex(yamux_config)
            .timeout(Duration::from_secs(20))
            .boxed()
    } else {
        dns_transport
            .map(|stream, _| Either::<EncryptedStream, RawStream>::Right(stream))
            .upgrade(Version::V1)
            .authenticate(noise_config)
            .multiplex(yamux_config)
            .timeout(Duration::from_secs(20))
            .boxed()
    };

    Ok(transport)
}

/// Instantiates the composite network behaviour logic.
///
/// Configures the following protocols:
/// * **Gossipsub**: Sets heartbeat based on `physics` vitality rates and enables strict validation.
/// * **Kademlia**: Initializes a memory store and sets the node to `Server` mode.
/// * **Identify**: Broadcasts the protocol version and public key.
/// * **Relay/DCUTR/AutoNAT**: Configures NAT traversal and relay capabilities.
///
/// # Arguments
/// * `local_key` - The node's identity keypair.
/// * `config` - Phalanx configuration settings.
/// * `physics` - Physics simulation state for timing calculations.
/// * `relay_client` - The pre-initialized relay client behaviour to inject.
fn build_behaviour(
    local_key: &Keypair,
    config: &PhalanxConfig,
    physics: &PhalanxPhysics,
    relay_client: relay::client::Behaviour,
) -> Result<PhalanxBehaviour, Box<dyn Error>> {
    let local_peer_id = local_key.public().to_peer_id();

    // CAPTURE IDENTITY
    let _local_node_id = NetworkId::from(local_peer_id);

    let gossip_heartbeat =
        VitalityRate::calculate(physics, PowerState::Normal, UnitInterval::new(0.0)).as_duration();

    let gossipsub = gossipsub::Behaviour::new(
        gossipsub::MessageAuthenticity::Signed(local_key.clone()),
        gossipsub::ConfigBuilder::default()
            .heartbeat_interval(gossip_heartbeat)
            .validation_mode(gossipsub::ValidationMode::Strict)
            .max_transmit_size(config.network.max_chunk_size_bytes * 2)
            .build()
            .map_err(std::io::Error::other)?,
    )?;

    let mut kademlia =
        kad::Behaviour::new(local_peer_id, kad::store::MemoryStore::new(local_peer_id));
    kademlia.set_mode(Some(kad::Mode::Server));

    let identify = identify::Behaviour::new(identify::Config::new(
        config.network.protocol_version.clone(),
        local_key.public(),
    ));

    let mdns = mdns::tokio::Behaviour::new(mdns::Config::default(), local_peer_id)?;
    let relay_server = relay::Behaviour::new(local_peer_id, relay::Config::default());
    let dcutr = dcutr::Behaviour::new(local_peer_id);
    let autonat = autonat::Behaviour::new(local_peer_id, autonat::Config::default());

    Ok(PhalanxBehaviour {
        gossipsub,
        mdns,
        kademlia,
        identify,
        relay_server,
        relay_client,
        dcutr,
        autonat,
    })
}

/// Reads and validates a libp2p Pre-Shared Key (PSK) from the filesystem.
///
/// Checks that the file exists and contains exactly 32 bytes.
/// Returns `None` if the file is missing, unreadable, or corrupt (invalid length).
pub fn load_swarm_key(path: &Path) -> Option<PreSharedKey> {
    match fs::read(path) {
        Ok(bytes) => {
            if bytes.len() == 32 {
                let mut arr = [0u8; 32];
                arr.copy_from_slice(&bytes);
                Some(PreSharedKey::new(arr))
            } else {
                tracing::error!(
                    "Swarm key at {:?} is corrupt (wrong length). Ignoring.",
                    path
                );
                None
            }
        }
        Err(_) => None,
    }
}

pub fn generate_swarm_key(path: &str) -> std::io::Result<()> {
    use dalek_rand::RngCore;
    let mut key = [0u8; 32];
    dalek_rand::OsRng.fill_bytes(&mut key);
    fs::write(path, key)
}

/// Constructs and initializes the main libp2p Swarm for the Phalanx node.
///
/// This orchestrator performs the following steps:
/// 1. Initializes the Relay Client to enable hole-punching and relay usage.
/// 2. Builds the base TCP/DNS transport with optional PNet (Pre-Shared Key) encryption.
/// 3. Configures the composite `PhalanxBehaviour` with Kademlia, Gossipsub, and Identify.
/// 4. Assembles the Swarm using `SwarmBuilder`, registering both the base transport and
///    the relay transport, and assigns the Tokio executor.
///
/// # Arguments
/// * `local_key` - The identity keypair for this node.
/// * `config` - Configuration for network parameters (chunk size, protocol version).
/// * `physics` - Simulation parameters used to calculate heartbeat intervals.
/// * `psk` - Optional Pre-Shared Key for private network clusters.
///
/// # Returns
/// * `Ok(Swarm<PhalanxBehaviour>)` - A fully configured Swarm ready to be driven.
/// * `Err(Box<dyn Error>)` - If transport creation or builder configuration fails.
pub fn setup_phalanx_swarm(
    local_key: Keypair,
    config: &PhalanxConfig,
    physics: &PhalanxPhysics,
    psk: Option<PreSharedKey>,
) -> Result<Swarm<PhalanxBehaviour>, Box<dyn Error>> {
    let local_peer_id = local_key.public().to_peer_id();
    tracing::info!(peer_id=%local_peer_id, "Initializing Network Stack...");

    let (relay_transport, relay_client) = relay::client::new(local_peer_id);

    let transport = build_base_transport(&local_key, psk)?;
    let behaviour = build_behaviour(&local_key, config, physics, relay_client)?;

    let swarm = SwarmBuilder::with_existing_identity(local_key.clone())
        .with_tokio()
        .with_other_transport(|_key| transport)?
        .with_other_transport(|key| {
            let noise_config = noise::Config::new(key).unwrap();
            let yamux_config = yamux::Config::default();

            relay_transport
                .upgrade(Version::V1)
                .authenticate(noise_config)
                .multiplex(yamux_config)
        })?
        .with_behaviour(|_| behaviour)?
        .with_swarm_config(|c| c.with_idle_connection_timeout(Duration::from_secs(60)))
        .build();

    Ok(swarm)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::primitives::identity::NetworkId;
    use libp2p::identity::Keypair;
    use std::fs::File;
    use std::io::Write;
    use tempfile::tempdir;

    fn get_test_config() -> (PhalanxConfig, PhalanxPhysics) {
        let config = PhalanxConfig::default();
        let physics = PhalanxPhysics::default_wan();
        (config, physics)
    }

    fn generate_test_identity() -> Keypair {
        Keypair::generate_ed25519()
    }

    #[test]
    fn test_swarm_key_io_roundtrip() {
        let dir = tempdir().expect("Failed to create temp dir");
        let file_path = dir.path().join("swarm.key");
        let path_str = file_path.to_str().unwrap();

        generate_swarm_key(path_str).expect("Failed to generate swarm key");
        assert!(file_path.exists());

        let loaded_key = load_swarm_key(&file_path);
        assert!(
            loaded_key.is_some(),
            "Should successfully load generated key"
        );

        let corrupt_path = dir.path().join("corrupt.key");
        let mut f = File::create(&corrupt_path).unwrap();
        f.write_all(b"short_key").unwrap();

        let loaded_corrupt = load_swarm_key(&corrupt_path);
        assert!(
            loaded_corrupt.is_none(),
            "Should reject key with invalid length"
        );
    }

    #[tokio::test]
    async fn test_behaviour_initialization() {
        let keypair = generate_test_identity();
        let (config, physics) = get_test_config();
        let local_peer_id = keypair.public().to_peer_id();

        let (_, relay_client_behaviour) = relay::client::new(local_peer_id);
        let result = build_behaviour(&keypair, &config, &physics, relay_client_behaviour);

        assert!(
            result.is_ok(),
            "PhalanxBehaviour should initialize with valid config"
        );
    }

    #[test]
    fn test_stronghold_announcement_query_generation() {
        let keypair = generate_test_identity();
        let (config, physics) = get_test_config();
        let local_peer_id = keypair.public().to_peer_id();
        let network_id = NetworkId::from(local_peer_id); // Explicit ID

        let (_, relay_client_behaviour) = relay::client::new(local_peer_id);
        let mut behaviour = build_behaviour(&keypair, &config, &physics, relay_client_behaviour)
            .expect("Setup failed");

        // Verify that the announcement returns a valid QueryId
        let result = behaviour.announce_stronghold(&network_id);
        assert!(
            result.is_some(),
            "Announce stronghold should succeed in a clean memory store"
        );
    }
}
