use futures::future::Either;
use libp2p::kad::RecordKey;
pub use libp2p::pnet::PreSharedKey;
use libp2p::{
    autonat, core::upgrade::Version, dcutr, gossipsub, identify, identity::Keypair, kad, mdns,
    noise, pnet, relay, swarm::NetworkBehaviour, tcp, yamux, PeerId, Swarm, SwarmBuilder,
    Transport,
}; // Required for Transport unification

use std::error::Error;
use std::fs;
use std::path::Path;
use std::time::Duration;

// Domain Imports
use crate::base::config::{PhalanxConfig, PhalanxPhysics};
use crate::base::types::{PowerState, UnitInterval, VitalityRate};

// --- CONSTANTS ---
pub type PhalanxKadStore = kad::store::MemoryStore;
pub const SERVICE_STORAGE: &[u8] = b"phalanx/service/storage/v1";
pub const STRONGHOLD_NAMESPACE: &[u8] = b"phalanx.stronghold.v1";

#[derive(Debug, thiserror::Error)]
pub enum DiscoveryError {
    #[error("Failed to serialize provider record")]
    SerializationError,
    #[error("DHT store is full or unavailable")]
    StorageError,
}

pub fn get_storage_key() -> RecordKey {
    RecordKey::new(&SERVICE_STORAGE)
}

/// The composite network behaviour struct for Phalanx.
///
/// This macro-derived struct aggregates specific network protocols (Gossipsub, Kademlia, etc.)
/// into a single behaviour that can be polled by the Swarm.
#[derive(NetworkBehaviour)]
#[behaviour(out_event = "PhalanxEvent")]
pub struct PhalanxBehaviour {
    // Writing this felt like a "welcome to Rust" moment.
    pub gossipsub: gossipsub::Behaviour,
    pub mdns: mdns::tokio::Behaviour,
    pub kademlia: kad::Behaviour<PhalanxKadStore>,
    pub identify: identify::Behaviour,
    pub relay_server: relay::Behaviour,
    pub relay_client: relay::client::Behaviour,
    pub dcutr: dcutr::Behaviour,
    pub autonat: autonat::Behaviour,
}

impl PhalanxBehaviour {
    /// Announces the local node as a Stronghold provider to the network.
    ///
    /// This publishes a provider record to the Kademlia DHT using the deterministic
    /// 'phalanx.stronghold.v1' namespace.
    /// This is NOT redundant. All nodes on the network can provide storage. This
    /// allows a the Stronghold binary to announce itself as a high availability node.
    pub fn announce_stronghold(&mut self) -> Result<kad::QueryId, DiscoveryError> {
        let record_key = RecordKey::new(&STRONGHOLD_NAMESPACE);

        tracing::info!(
            target: "phalanx::transport",
            "Announcing local node as Stronghold provider"
        );

        self.kademlia
            .start_providing(record_key)
            .map_err(|_| DiscoveryError::StorageError)
    }

    /// Initiates a DHT query to find active Stronghold nodes.
    ///
    /// Triggers a `get_providers` query. Results are returned asynchronously via
    /// SwarmEvent::Behaviour(PhalanxBehaviourEvent::Kademlia(...)).
    pub fn find_strongholds(&mut self) -> kad::QueryId {
        let record_key = RecordKey::new(&STRONGHOLD_NAMESPACE);

        tracing::info!(
            target: "phalanx::transport",
            "Initiating discovery for Stronghold providers"
        );

        self.kademlia.get_providers(record_key)
    }
}

/// Enumeration of all possible events generated by the `PhalanxBehaviour`.
///
/// Acts as a unified wrapper for protocol-specific events (e.g., Gossipsub messages, Kademlia query results),
/// allowing the main event loop to match on a single type.
#[derive(Debug)]
pub enum PhalanxEvent {
    // Types on types! This was my "welcome to Rust" moment.
    Gossipsub(gossipsub::Event),
    Mdns(mdns::Event),
    Kademlia(kad::Event),
    Identify(Box<identify::Event>),
    RelayServer(relay::Event),
    RelayClient(relay::client::Event),
    Dcutr(dcutr::Event),
    Autonat(autonat::Event),
}

impl From<gossipsub::Event> for PhalanxEvent {
    fn from(v: gossipsub::Event) -> Self {
        Self::Gossipsub(v)
    }
}
impl From<mdns::Event> for PhalanxEvent {
    fn from(v: mdns::Event) -> Self {
        Self::Mdns(v)
    }
}
impl From<kad::Event> for PhalanxEvent {
    fn from(v: kad::Event) -> Self {
        Self::Kademlia(v)
    }
}
impl From<identify::Event> for PhalanxEvent {
    fn from(v: identify::Event) -> Self {
        Self::Identify(Box::new(v))
    }
}
impl From<relay::Event> for PhalanxEvent {
    fn from(v: relay::Event) -> Self {
        Self::RelayServer(v)
    }
}
impl From<relay::client::Event> for PhalanxEvent {
    fn from(v: relay::client::Event) -> Self {
        Self::RelayClient(v)
    }
}
impl From<dcutr::Event> for PhalanxEvent {
    fn from(v: dcutr::Event) -> Self {
        Self::Dcutr(v)
    }
}
impl From<autonat::Event> for PhalanxEvent {
    fn from(v: autonat::Event) -> Self {
        Self::Autonat(v)
    }
}

/// Constructs the foundational transport stack for the node.
///
/// This stack supports TCP and DNS, with optional PNet (Pre-Shared Key) encryption for private swarms.
/// It upgrades connections using Noise for security and Yamux for stream multiplexing.
///
/// # Arguments
/// * `local_key` - The node's identity keypair, used for Noise handshake.
/// * `psk` - Optional Pre-Shared Key. If provided, the transport is wrapped in a PNet layer.
///
/// # Returns
/// Returns a boxed transport that unifies the types of Encrypted (PNet) and Raw streams
/// into a single `Either` type, ensuring type consistency for the SwarmBuilder.
fn build_base_transport(
    local_key: &Keypair,
    psk: Option<PreSharedKey>,
) -> Result<
    libp2p::core::transport::Boxed<(PeerId, libp2p::core::muxing::StreamMuxerBox)>,
    Box<dyn Error>,
> {
    let noise_config = noise::Config::new(local_key)?;
    let yamux_config = yamux::Config::default();

    let base_transport = tcp::tokio::Transport::new(tcp::Config::default().nodelay(true));
    let dns_transport = libp2p::dns::tokio::Transport::system(base_transport)?;

    // Define the Stream Type Alias to make the annotation readable- this gave me nightmares.
    // The "Right" side is a raw TCP Stream
    type RawStream = libp2p::tcp::tokio::TcpStream;
    // The "Left" side is a TCP Stream wrapped in PNet encryption
    type EncryptedStream = libp2p::pnet::PnetOutput<RawStream>;

    let transport = if let Some(key) = psk {
        let pnet_config = pnet::PnetConfig::new(key);
        dns_transport
            .and_then(move |socket, _| pnet_config.handshake(socket))
            // Explicitly tell compiler the Right side is RawStream
            .map(|stream, _| Either::<EncryptedStream, RawStream>::Left(stream))
            .upgrade(Version::V1)
            .authenticate(noise_config)
            .multiplex(yamux_config)
            .timeout(Duration::from_secs(20))
            .boxed()
    } else {
        dns_transport
            // Explicitly tell compiler the Left side is EncryptedStream
            .map(|stream, _| Either::<EncryptedStream, RawStream>::Right(stream))
            .upgrade(Version::V1)
            .authenticate(noise_config)
            .multiplex(yamux_config)
            .timeout(Duration::from_secs(20))
            .boxed()
    };

    Ok(transport)
}

/// Instantiates the composite network behaviour logic.
///
/// Configures the following protocols:
/// * **Gossipsub**: Sets heartbeat based on `physics` vitality rates and enables strict validation.
/// * **Kademlia**: Initializes a memory store and sets the node to `Server` mode.
/// * **Identify**: Broadcasts the protocol version and public key.
/// * **Relay/DCUTR/AutoNAT**: Configures NAT traversal and relay capabilities.
///
/// # Arguments
/// * `local_key` - The node's identity keypair.
/// * `config` - Phalanx configuration settings.
/// * `physics` - Physics simulation state for timing calculations.
/// * `relay_client` - The pre-initialized relay client behaviour to inject.
fn build_behaviour(
    local_key: &Keypair,
    config: &PhalanxConfig,
    physics: &PhalanxPhysics,
    relay_client: relay::client::Behaviour,
) -> Result<PhalanxBehaviour, Box<dyn Error>> {
    let local_peer_id = local_key.public().to_peer_id();

    // A. Gossipsub
    let gossip_heartbeat =
        VitalityRate::calculate(physics, PowerState::Normal, UnitInterval::new(0.0)).as_duration();

    let gossipsub = gossipsub::Behaviour::new(
        gossipsub::MessageAuthenticity::Signed(local_key.clone()),
        gossipsub::ConfigBuilder::default()
            .heartbeat_interval(gossip_heartbeat)
            .validation_mode(gossipsub::ValidationMode::Strict)
            .max_transmit_size(config.network.max_chunk_size_bytes as usize * 2)
            .build()
            .map_err(|msg| std::io::Error::new(std::io::ErrorKind::Other, msg))?, // FIX: Explicit std::io
    )?;

    // B. Kademlia
    let mut kademlia =
        kad::Behaviour::new(local_peer_id, kad::store::MemoryStore::new(local_peer_id));
    kademlia.set_mode(Some(kad::Mode::Server));

    // C. Identify
    let identify = identify::Behaviour::new(identify::Config::new(
        config.network.protocol_version.clone(),
        local_key.public(),
    ));

    // D. Others
    let mdns = mdns::tokio::Behaviour::new(mdns::Config::default(), local_peer_id)?;

    // Relay Server (For hosting)
    let relay_server = relay::Behaviour::new(local_peer_id, relay::Config::default());

    let dcutr = dcutr::Behaviour::new(local_peer_id);
    let autonat = autonat::Behaviour::new(local_peer_id, autonat::Config::default());

    Ok(PhalanxBehaviour {
        gossipsub,
        mdns,
        kademlia,
        identify,
        relay_server,
        relay_client, // Injected
        dcutr,
        autonat,
    })
}

/// Reads and validates a libp2p Pre-Shared Key (PSK) from the filesystem.
///
/// Checks that the file exists and contains exactly 32 bytes.
/// Returns `None` if the file is missing, unreadable, or corrupt (invalid length).
pub fn load_swarm_key(path: &Path) -> Option<PreSharedKey> {
    match fs::read(path) {
        Ok(bytes) => {
            if bytes.len() == 32 {
                let mut arr = [0u8; 32];
                arr.copy_from_slice(&bytes);
                Some(PreSharedKey::new(arr))
            } else {
                tracing::error!(
                    "Swarm key at {:?} is corrupt (wrong length). Ignoring.",
                    path
                );
                None
            }
        }
        Err(_) => None,
    }
}

/// Generates a new cryptographically secure 32-byte Pre-Shared Key (PSK) and writes it to disk.
///
/// Uses `dalek_rand::OsRng` as the randomness source.
/// Returns `std::io::Result<()>` indicating success or failure of the file write operation.
pub fn generate_swarm_key(path: &str) -> std::io::Result<()> {
    use dalek_rand::RngCore;
    let mut key = [0u8; 32];
    dalek_rand::OsRng.fill_bytes(&mut key);
    fs::write(path, key)
}

/// Constructs and initializes the main libp2p Swarm for the Phalanx node.
///
/// This orchestrator performs the following steps:
/// 1. Initializes the Relay Client to enable hole-punching and relay usage.
/// 2. Builds the base TCP/DNS transport with optional PNet (Pre-Shared Key) encryption.
/// 3. Configures the composite `PhalanxBehaviour` with Kademlia, Gossipsub, and Identify.
/// 4. Assembles the Swarm using `SwarmBuilder`, registering both the base transport and
///    the relay transport, and assigns the Tokio executor.
///
/// # Arguments
/// * `local_key` - The identity keypair for this node.
/// * `config` - Configuration for network parameters (chunk size, protocol version).
/// * `physics` - Simulation parameters used to calculate heartbeat intervals.
/// * `psk` - Optional Pre-Shared Key for private network clusters.
///
/// # Returns
/// * `Ok(Swarm<PhalanxBehaviour>)` - A fully configured Swarm ready to be driven.
/// * `Err(Box<dyn Error>)` - If transport creation or builder configuration fails.
pub fn setup_phalanx_swarm(
    local_key: Keypair,
    config: &PhalanxConfig,
    physics: &PhalanxPhysics,
    psk: Option<PreSharedKey>,
) -> Result<Swarm<PhalanxBehaviour>, Box<dyn Error>> {
    let local_peer_id = local_key.public().to_peer_id();
    tracing::info!(peer_id=%local_peer_id, "Initializing Network Stack...");

    // 1. Initialize Relay Client (Returns Transport + Behaviour)
    let (relay_transport, relay_client) = relay::client::new(local_peer_id);

    // 2. Build Base Transport (TCP/DNS/Noise/Yamux)
    let transport = build_base_transport(&local_key, psk)?;

    // 3. Build Behaviour (Inject Relay Client)
    let behaviour = build_behaviour(&local_key, config, physics, relay_client)?;

    // 4. Build Swarm (NEW API v0.56+)
    let swarm = SwarmBuilder::with_existing_identity(local_key.clone())
        .with_tokio() // Set the executor first
        // Primary Transport (TCP/DNS/PNet)
        // We wrap the pre-built transport in a closure to satisfy the API
        .with_other_transport(|_key| transport)?
        // Secondary Transport (Relay)
        .with_other_transport(|key| {
            let noise_config = noise::Config::new(key).unwrap();
            let yamux_config = yamux::Config::default();

            relay_transport
                .upgrade(Version::V1)
                .authenticate(noise_config)
                .multiplex(yamux_config)
        })?
        // Behaviour & Configuration
        .with_behaviour(|_| behaviour)?
        .with_swarm_config(|c| c.with_idle_connection_timeout(Duration::from_secs(60)))
        .build();

    Ok(swarm)
}

#[cfg(test)]
mod tests {
    use super::*;
    use libp2p::identity::Keypair;
    use std::fs::File;
    use std::io::Write;
    use tempfile::tempdir;

    // --- TEST HELPERS ---

    fn get_test_config() -> (PhalanxConfig, PhalanxPhysics) {
        // Assuming Default or specific constructors exist based on imports
        // If specific values are needed for validation, set them here.
        let config = PhalanxConfig::default();
        let physics = PhalanxPhysics::default_wan(); // or test_profile()
        (config, physics)
    }

    fn generate_test_identity() -> Keypair {
        Keypair::generate_ed25519()
    }

    // --- TESTS ---

    #[test]
    fn test_swarm_key_io_roundtrip() {
        // 1. Setup isolated temp directory
        let dir = tempdir().expect("Failed to create temp dir");
        let file_path = dir.path().join("swarm.key");
        let path_str = file_path.to_str().unwrap();

        // 2. Generate Key
        generate_swarm_key(path_str).expect("Failed to generate swarm key");

        // 3. Verify file exists
        assert!(file_path.exists());

        // 4. Load Key
        let loaded_key = load_swarm_key(&file_path);
        assert!(
            loaded_key.is_some(),
            "Should successfully load generated key"
        );

        // 5. Verify corruption handling
        let corrupt_path = dir.path().join("corrupt.key");
        let mut f = File::create(&corrupt_path).unwrap();
        f.write_all(b"short_key").unwrap(); // Write invalid length

        let loaded_corrupt = load_swarm_key(&corrupt_path);
        assert!(
            loaded_corrupt.is_none(),
            "Should reject key with invalid length"
        );
    }

    #[tokio::test]
    async fn test_transport_construction_no_psk() {
        let keypair = generate_test_identity();

        // Attempt to build base transport without PSK
        let result = build_base_transport(&keypair, None);

        assert!(
            result.is_ok(),
            "Transport construction should succeed without PSK"
        );
    }

    #[tokio::test]
    async fn test_transport_construction_with_psk() {
        let keypair = generate_test_identity();

        // Manually construct a PSK
        let mut bytes = [0u8; 32];
        bytes[0] = 1; // arbitrary
        let psk = PreSharedKey::new(bytes);

        // Attempt to build base transport with PSK
        let result = build_base_transport(&keypair, Some(psk));

        assert!(
            result.is_ok(),
            "Transport construction should succeed with PSK"
        );
    }

    #[tokio::test]
    async fn test_behaviour_initialization() {
        let keypair = generate_test_identity();
        let (config, physics) = get_test_config();
        let local_peer_id = keypair.public().to_peer_id();

        // Initialize relay client (dependency injection)
        let (_, relay_client_behaviour) = relay::client::new(local_peer_id);

        let result = build_behaviour(&keypair, &config, &physics, relay_client_behaviour);

        assert!(
            result.is_ok(),
            "PhalanxBehaviour should initialize with valid config"
        );

        let behaviour = result.unwrap();
        // Verify Kademlia mode is Server (as set in build_behaviour)
        // Note: access to internal mode might be restricted, but we verify the struct exists
        assert!(matches!(behaviour.kademlia, kad::Behaviour { .. }));
    }

    #[tokio::test]
    async fn test_full_swarm_setup() {
        let keypair = generate_test_identity();
        let expected_peer_id = keypair.public().to_peer_id();
        let (config, physics) = get_test_config();

        // Test the main orchestrator function
        let swarm_result = setup_phalanx_swarm(
            keypair, &config, &physics, None, // No PSK for this test
        );

        assert!(
            swarm_result.is_ok(),
            "SwarmBuilder pipeline should complete without error"
        );

        let swarm = swarm_result.unwrap();
        assert_eq!(
            *swarm.local_peer_id(),
            expected_peer_id,
            "Swarm should be initialized with the provided identity"
        );
    }
}

#[cfg(test)]
mod discovery_logic_tests {
    use super::*;
    use crate::base::config::{PhalanxConfig, PhalanxPhysics};
    use libp2p::identity::Keypair;

    fn setup_test_behaviour() -> PhalanxBehaviour {
        let id_keys = Keypair::generate_ed25519();
        let config = PhalanxConfig::default();
        let physics = PhalanxPhysics::default();

        // Mocking the relay client for behaviour initialization
        let local_peer_id = id_keys.public().to_peer_id();
        let (_, relay_client) = libp2p::relay::client::new(local_peer_id);

        build_behaviour(&id_keys, &config, &physics, relay_client)
            .expect("Failed to initialize PhalanxBehaviour for testing")
    }

    #[test]
    fn test_stronghold_announcement_query_generation() {
        let mut behaviour = setup_test_behaviour();

        // Verify that the announcement returns a valid QueryId and does not panic
        let result = behaviour.announce_stronghold();
        assert!(
            result.is_ok(),
            "Announce stronghold should succeed in a clean memory store"
        );
    }

    #[test]
    fn test_find_strongholds_namespace_alignment() {
        let mut behaviour = setup_test_behaviour();

        // Initiate discovery
        let query_id = behaviour.find_strongholds();

        // In libp2p v0.56.x, we verify that the query is tracked in the Kademlia state
        // This confirms the namespace was correctly transformed into a RecordKey
        assert!(
            behaviour.kademlia.query(&query_id).is_some(),
            "The find_strongholds query must be active in the Kademlia engine"
        );
    }

    #[test]
    fn test_namespace_consistency() {
        let storage_key = get_storage_key();
        let stronghold_key = RecordKey::new(&STRONGHOLD_NAMESPACE);

        assert_ne!(
            storage_key, stronghold_key,
            "Storage and Stronghold namespaces must remain distinct to prevent query pollution"
        );
    }
}
