use libp2p::{autonat, dcutr, gossipsub, identify, kad, mdns, relay, request_response};
use phalanx_proto::archive::{ArchiveReceipt, ArchiveRequest};
use phalanx_proto::retrieval::RecordingRequest;
use phalanx_proto::retrieval::RecordingResponse;
use std::convert::Infallible;

/// Enumeration of all possible events generated by the `PhalanxBehaviour`.
#[derive(Debug)]
pub enum PhalanxEvent {
    Gossipsub(gossipsub::Event),
    Mdns(mdns::Event),
    Kademlia(kad::Event),
    Identify(Box<identify::Event>),
    RelayServer(relay::Event),
    RelayClient(relay::client::Event),
    Dcutr(dcutr::Event),
    Autonat(autonat::Event),
    Retrieval(request_response::Event<RecordingRequest, RecordingResponse>),
    Archive(request_response::Event<ArchiveRequest, ArchiveReceipt>),
}

impl From<gossipsub::Event> for PhalanxEvent {
    fn from(v: gossipsub::Event) -> Self {
        Self::Gossipsub(v)
    }
}
impl From<mdns::Event> for PhalanxEvent {
    fn from(v: mdns::Event) -> Self {
        Self::Mdns(v)
    }
}
impl From<kad::Event> for PhalanxEvent {
    fn from(v: kad::Event) -> Self {
        Self::Kademlia(v)
    }
}
impl From<identify::Event> for PhalanxEvent {
    fn from(v: identify::Event) -> Self {
        Self::Identify(Box::new(v))
    }
}
impl From<relay::Event> for PhalanxEvent {
    fn from(v: relay::Event) -> Self {
        Self::RelayServer(v)
    }
}
impl From<relay::client::Event> for PhalanxEvent {
    fn from(v: relay::client::Event) -> Self {
        Self::RelayClient(v)
    }
}
impl From<dcutr::Event> for PhalanxEvent {
    fn from(v: dcutr::Event) -> Self {
        Self::Dcutr(v)
    }
}
impl From<autonat::Event> for PhalanxEvent {
    fn from(v: autonat::Event) -> Self {
        Self::Autonat(v)
    }
}

impl From<request_response::Event<RecordingRequest, RecordingResponse>> for PhalanxEvent {
    fn from(event: request_response::Event<RecordingRequest, RecordingResponse>) -> Self {
        PhalanxEvent::Retrieval(event)
    }
}

impl From<request_response::Event<ArchiveRequest, ArchiveReceipt>> for PhalanxEvent {
    fn from(event: request_response::Event<ArchiveRequest, ArchiveReceipt>) -> Self {
        PhalanxEvent::Archive(event)
    }
}

/// E1 FIX: connection_limits::Behaviour emits Infallible (never fires),
/// but the NetworkBehaviour derive macro requires a From impl for all sub-behaviours.
impl From<Infallible> for PhalanxEvent {
    fn from(v: Infallible) -> Self {
        match v {} // Infallible can never be constructed
    }
}
