/// Enumeration of all possible events generated by the `PhalanxBehaviour`.
#[derive(Debug)]
pub enum PhalanxEvent {
    Gossipsub(gossipsub::Event),
    Mdns(mdns::Event),
    Kademlia(kad::Event),
    Identify(Box<identify::Event>),
    RelayServer(relay::Event),
    RelayClient(relay::client::Event),
    Dcutr(dcutr::Event),
    Autonat(autonat::Event),
    Retrieval(request_response::Event<VolleyRequest, VolleyResponse>),
}

impl From<gossipsub::Event> for PhalanxEvent {
    fn from(v: gossipsub::Event) -> Self {
        Self::Gossipsub(v)
    }
}
impl From<mdns::Event> for PhalanxEvent {
    fn from(v: mdns::Event) -> Self {
        Self::Mdns(v)
    }
}
impl From<kad::Event> for PhalanxEvent {
    fn from(v: kad::Event) -> Self {
        Self::Kademlia(v)
    }
}
impl From<identify::Event> for PhalanxEvent {
    fn from(v: identify::Event) -> Self {
        Self::Identify(Box::new(v))
    }
}
impl From<relay::Event> for PhalanxEvent {
    fn from(v: relay::Event) -> Self {
        Self::RelayServer(v)
    }
}
impl From<relay::client::Event> for PhalanxEvent {
    fn from(v: relay::client::Event) -> Self {
        Self::RelayClient(v)
    }
}
impl From<dcutr::Event> for PhalanxEvent {
    fn from(v: dcutr::Event) -> Self {
        Self::Dcutr(v)
    }
}
impl From<autonat::Event> for PhalanxEvent {
    fn from(v: autonat::Event) -> Self {
        Self::Autonat(v)
    }
}

impl From<request_response::Event<VolleyRequest, VolleyResponse>> for PhalanxEvent {
    fn from(event: request_response::Event<VolleyRequest, VolleyResponse>) -> Self {
        PhalanxEvent::Retrieval(event)
    }
}
