use phalanx_core::base::config::{PhalanxConfig, PhalanxPhysics};
use phalanx_core::base::engine::{NoOpJournal, PhalanxEngine, SyncReputationCache};
use phalanx_core::primitives::identity::init_identity;
use phalanx_core::security::trust::TrustRegistry;
use phalanx_core::transport::libp2p_adapter::Libp2pAdapter;
use phalanx_core::transport::swarm::setup_phalanx_swarm;
use std::ffi::CStr;
use std::os::raw::c_char;
use std::path::Path;
use std::ptr;
use std::sync::Arc;
use tokio::sync::mpsc;

#[cfg(target_os = "android")]
pub mod jni;

/// Type alias to provide a concrete, monomorphized type for the C-ABI boundary.
pub type MobileEngine = PhalanxEngine<Libp2pAdapter, NoOpJournal>;

/// Initializes the Phalanx storage engine.
///
/// # Safety
/// The caller must ensure `storage_path` is a valid, null-terminated C-string
/// pointer. Passing a null or dangling pointer will cause Undefined Behavior.
#[no_mangle]
pub unsafe extern "C" fn phalanx_engine_new(storage_path: *const c_char) -> *mut MobileEngine {
    if storage_path.is_null() {
        return ptr::null_mut();
    }

    let c_str = CStr::from_ptr(storage_path);
    let Ok(path_str) = c_str.to_str() else {
        return ptr::null_mut();
    };

    // Establish Configuration
    let mut config = PhalanxConfig::default();
    config.storage.vault_path = path_str.to_string();
    let physics = PhalanxPhysics::default_wan();
    let identity = init_identity(
        Path::new(path_str)
            .join("identity.pem")
            .to_str()
            .unwrap_or("identity.pem"),
    )
    .unwrap_or_default();
    let reputation_cache = Arc::new(SyncReputationCache::default());

    // Unitary Async Initialization
    // We build a single runtime to drive the entire initialization sequence.
    let engine_result = std::thread::spawn({
        let config = config.clone();
        let identity = identity.clone();
        let reputation_cache = reputation_cache.clone();

        move || {
            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("Failed to build Mobile Runtime");

            rt.block_on(async {
                // T0: Build Trust (Guardian Logic)
                let trust_registry = TrustRegistry::build(&config).await;

                // T1: Setup Network (Transport Logic)
                let swarm = setup_phalanx_swarm(
                    identity.to_libp2p_keypair(),
                    &config,
                    &physics,
                    None,
                    reputation_cache.clone(),
                )
                .map_err(|e| format!("Swarm Failure: {e}"))?;

                let adapter = Libp2pAdapter::new(swarm);
                let (discovery_tx, discovery_rx) = mpsc::channel(100);
                // T2: Initialize Engine (Sentinel Logic)
                // Now natively awaited inside the block_on
                PhalanxEngine::new(
                    config,
                    identity,
                    adapter,
                    NoOpJournal,
                    trust_registry,
                    reputation_cache,
                    discovery_rx,
                    discovery_tx,
                )
                .await
                .map_err(|e| format!("Engine Failure: {e}"))
            })
        }
    })
    .join()
    .expect("FFI Initialization panicked");

    match engine_result {
        Ok(engine) => Box::into_raw(Box::new(engine)),
        Err(e) => {
            eprintln!("Phalanx FFI Error: {e}");
            ptr::null_mut()
        }
    }
}
/// Frees the Phalanx Engine pointer.
///
/// # Safety
/// * `ptr` must be a valid pointer generated by `phalanx_engine_new`.
/// * `ptr` must not be null (though the implementation handles nulls gracefully).
/// * This function must strictly be called only once per pointer to prevent Double Free.
#[no_mangle]
pub unsafe extern "C" fn phalanx_engine_free(ptr: *mut MobileEngine) {
    if !ptr.is_null() {
        // SAFETY: We explicitly trust the JNI/C caller to pass a valid pointer
        // derived from phalanx_engine_new.
        let _ = Box::from_raw(ptr);
    }
}
