use phalanx_core::base::config::{PhalanxConfig, PhalanxPhysics};
use phalanx_core::base::engine::{NoOpJournal, PhalanxEngine};
use phalanx_core::primitives::identity::init_identity;
use phalanx_core::transport::libp2p_adapter::Libp2pAdapter;
use phalanx_core::transport::swarm::setup_phalanx_swarm;
use std::ffi::CStr;
use std::os::raw::c_char;
use std::path::Path;
use std::ptr;

#[cfg(target_os = "android")]
pub mod jni;

/// Type alias to provide a concrete, monomorphized type for the C-ABI boundary.
pub type MobileEngine = PhalanxEngine<Libp2pAdapter, NoOpJournal>;

/// Initializes the Phalanx storage engine.
///
/// # Safety
/// The caller must ensure `storage_path` is a valid, null-terminated C-string
/// pointer. Passing a null or dangling pointer will cause Undefined Behavior.
#[no_mangle]
pub unsafe extern "C" fn phalanx_engine_new(storage_path: *const c_char) -> *mut MobileEngine {
    if storage_path.is_null() {
        return ptr::null_mut();
    }

    let c_str = CStr::from_ptr(storage_path);

    let Ok(path_str) = c_str.to_str() else {
        return ptr::null_mut(); // Invalid UTF-8
    };

    // 1. Establish Configuration & Identity (Mobile context usually implies WAN)
    let mut config = PhalanxConfig::default();
    config.storage.vault_path = path_str.to_string();
    let physics = PhalanxPhysics::default_wan();

    let identity_path = Path::new(path_str).join("identity.pem");
    let identity_path_str = identity_path.to_str().unwrap_or("identity.pem");
    let identity = init_identity(identity_path_str).unwrap_or_default();
    let network_keypair = identity.to_libp2p_keypair();

    // 2. Instantiate the Production Network Adapter
    let swarm = match setup_phalanx_swarm(network_keypair, &config, &physics, None) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("Failed to initialize mobile swarm: {e}");
            return ptr::null_mut();
        }
    };

    let network_adapter = Libp2pAdapter::new(swarm);

    // 3. Initialize the engine synchronously with the injected adapter
    match PhalanxEngine::new_at_path(path_str, network_adapter) {
        Ok(engine) => {
            // Success: Move engine to heap and return raw pointer
            Box::into_raw(Box::new(engine))
        }
        Err(e) => {
            // Failure: Log error and return Null
            eprintln!("Failed to init Phalanx Engine: {e}");
            ptr::null_mut()
        }
    }
}

/// Frees the Phalanx Engine pointer.
///
/// # Safety
/// * `ptr` must be a valid pointer generated by `phalanx_engine_new`.
/// * `ptr` must not be null (though the implementation handles nulls gracefully).
/// * This function must strictly be called only once per pointer to prevent Double Free.
#[no_mangle]
pub unsafe extern "C" fn phalanx_engine_free(ptr: *mut MobileEngine) {
    if !ptr.is_null() {
        // SAFETY: We explicitly trust the JNI/C caller to pass a valid pointer
        // derived from phalanx_engine_new.
        let _ = Box::from_raw(ptr);
    }
}
