/* Generated by cbindgen — do not edit manually. */

#ifndef PHALANX_FFI_H
#define PHALANX_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Pixel format of the interleaved chroma plane from the camera.
 *
 * Android's Camera2 API delivers NV21 (VU interleaved).
 * iOS AVFoundation delivers NV12 (UV interleaved).
 * Both share the same Y plane — only the chroma byte order differs.
 */
typedef enum PixelFormat {
  /**
   * NV21: V then U interleaved. Android default.
   */
  NV21 = 0,
  /**
   * NV12: U then V interleaved. iOS default.
   */
  NV12 = 1,
} PixelFormat;

/**
 * FFI error codes returned by all `extern "C"` functions.
 *
 * Contract: every public FFI function returns `PhalanxError as i32`.
 * The Dart wrapper maps these to typed exceptions.
 */
enum PhalanxError {
  /**
   * Operation completed successfully.
   */
  OK = 0,
  /**
   * A null pointer was passed where a valid pointer was required.
   */
  NULL_POINTER = -1,
  /**
   * The handle is in an invalid state for the requested operation.
   */
  INVALID_STATE = -2,
  /**
   * A C-string argument contained invalid UTF-8.
   */
  INVALID_UTF8 = -3,
  /**
   * Engine bootstrap failed (config, identity, vault, swarm, or sentinel).
   */
  BOOT_FAILED = -4,
  /**
   * The engine is already running; duplicate `phalanx_start` calls.
   */
  ALREADY_RUNNING = -5,
  /**
   * The engine is not running; operation requires a running engine.
   */
  NOT_RUNNING = -6,
  /**
   * An internal mpsc/oneshot channel was closed unexpectedly.
   */
  CHANNEL_CLOSED = -7,
  /**
   * A trust registry operation failed.
   */
  TRUST_ERROR = -8,
  /**
   * A playback operation failed.
   */
  PLAYBACK_ERROR = -9,
  /**
   * Configuration loading or validation failed.
   */
  CONFIG_ERROR = -10,
  /**
   * Recording is already active; duplicate `phalanx_start_recording` calls.
   */
  ALREADY_RECORDING = -11,
  /**
   * No active recording to stop or push frames to.
   */
  NOT_RECORDING = -12,
  /**
   * Cryptographic Forgetting: revocation failed (bad mnemonic, key mismatch, or storage error).
   */
  REVOCATION_FAILED = -13,
};
typedef int32_t PhalanxError;

/**
 * The opaque handle type exposed to C/Dart.
 *
 * This is the single point of contact between Rust and the outside world.
 * All fields are behind synchronization primitives suitable for concurrent
 * FFI access from arbitrary Dart isolates.
 */
typedef struct PhalanxHandle PhalanxHandle;

/**
 * Opaque playback session — owns the video + audio receivers.
 *
 * Flutter holds a `Pointer<Void>` to this. Each poll is a pure `try_recv()`
 * on the session's receiver. No Mutex. Single-owner (Flutter's main isolate).
 */
typedef struct PlaybackSession PlaybackSession;

/**
 * Sign a BLE auth challenge from a remote peer.
 *
 * Flutter calls this when it receives a BLE challenge. Rust signs with the node's
 * Ed25519 key. Flutter sends the resulting signature back over BLE.
 *
 * # Parameters
 * * `handle` — valid PhalanxHandle pointer
 * * `challenger_did_ptr/len` — the remote peer's DID (UTF-8 bytes)
 * * `nonce_ptr` — pointer to exactly 32 bytes of challenge nonce
 * * `out_signature` — pointer to 64-byte buffer for the Ed25519 signature output
 *
 * # Safety
 * All pointers must be valid. `out_signature` must point to at least 64 writable bytes.
 */

int32_t phalanx_sign_ble_challenge(const struct PhalanxHandle *handle,
                                   const uint8_t *challenger_did_ptr,
                                   uintptr_t challenger_did_len,
                                   const uint8_t *nonce_ptr,
                                   uint8_t *out_signature)
;

/**
 * Verify a BLE auth response from a remote peer.
 *
 * Flutter calls this after receiving a BLE auth response. Rust verifies the
 * Ed25519 signature. Returns 0 if verified, negative error code if not.
 *
 * # Parameters
 * * `handle` — valid PhalanxHandle pointer
 * * `responder_did_ptr/len` — the remote peer's DID (UTF-8 bytes)
 * * `our_nonce_ptr` — pointer to the 32-byte nonce we sent in our challenge
 * * `signature_ptr` — pointer to the 64-byte Ed25519 signature from the remote peer
 *
 * # Safety
 * All pointers must be valid with the specified lengths.
 */

int32_t phalanx_verify_ble_peer(const struct PhalanxHandle *handle,
                                const uint8_t *responder_did_ptr,
                                uintptr_t responder_did_len,
                                const uint8_t *our_nonce_ptr,
                                const uint8_t *signature_ptr)
;

/**
 * Starts PRNU calibration. Allocates the frame buffer.
 *
 * Call this before pushing calibration frames. Returns error if calibration
 * is already in progress.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_calibration_start(const struct PhalanxHandle *handle) ;

/**
 * Pushes a calibration frame. Runs ForensicLens on the Y-plane and stores
 * the resulting metrics.
 *
 * Call this for each calibration frame (minimum 10, maximum 100).
 * Returns error if calibration is not in progress or buffer is full.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `y_plane` must point to `y_len` valid bytes of Y-plane data.
 */

int32_t phalanx_calibration_push_frame(const struct PhalanxHandle *handle,
                                       const uint8_t *y_plane,
                                       uint32_t y_len,
                                       uint32_t width,
                                       uint32_t height)
;

/**
 * Finishes calibration, computes the PRNU floor, and writes it to `out_prnu_floor`.
 *
 * Clears the calibration buffer regardless of success/failure.
 * On success, the calibrated floor is stored — the caller (Flutter) should
 * persist it to the device config.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_prnu_floor` must be a valid pointer to receive the f32 result.
 */
 int32_t phalanx_calibration_finish(const struct PhalanxHandle *handle, float *out_prnu_floor) ;

/**
 * Starts a new recording session.
 *
 * Generates a unique `RecordingId` and sets the handle into recording mode.
 * Returns the recording ID through `out_recording_id` (caller frees with `phalanx_free_string`).
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_recording_id` must be a valid pointer to receive the C string.
 */
 int32_t phalanx_start_recording(struct PhalanxHandle *handle, char **out_recording_id) ;

/**
 * Stops the current recording session.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_stop_recording(struct PhalanxHandle *handle) ;

/**
 * Pushes a raw YUV video frame through the forensic pipeline.
 *
 * Pipeline:
 * 1. `ForensicLens::analyze()` — PRNU variance, Moiré detection, Laplacian energy (Y-plane only, 256×256 center crop, 64KB, fits L1)
 * 2. `compress_frame()` — full-color YUV→JPEG via turbojpeg (no RGB conversion)
 * 3. `create_video_shard()` — shard with forensic metrics
 * 4. `try_send` to video channel → `MediaEgressActor` handles mesh distribution
 *
 * Uses `try_send` — returns immediately, drops on backpressure.
 * Power-state-aware FPS is governed by Rust via `target_fps()`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `y_plane` must point to `y_len` valid bytes of raw luma data (`width * height`).
 * * `uv_plane` must point to `uv_len` valid bytes of interleaved chroma (`width * height / 2`).
 * * `recording_id` must be a valid null-terminated C string (returned from `phalanx_start_recording`).
 */

int32_t phalanx_push_video_frame(struct PhalanxHandle *handle,
                                 const uint8_t *y_plane,
                                 uint32_t y_len,
                                 const uint8_t *uv_plane,
                                 uint32_t uv_len,
                                 uint32_t width,
                                 uint32_t height,
                                 enum PixelFormat pixel_format,
                                 const char *recording_id,
                                 uint64_t _timestamp_ms)
;

/**
 * Pushes a raw PCM audio frame through the forensic pipeline.
 *
 * Pipeline:
 * 1. `create_audio_shard()` — wraps PCM data with LZ4 compression
 * 2. `try_send` to audio channel → `MediaEgressActor` encrypts + handles mesh distribution
 *
 * Uses `try_send` — returns immediately, drops on backpressure.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `pcm_data` must point to `pcm_len` valid bytes of 16-bit LE PCM audio.
 * * `recording_id` must be a valid null-terminated C string.
 */

int32_t phalanx_push_audio_frame(struct PhalanxHandle *handle,
                                 const uint8_t *pcm_data,
                                 uint32_t pcm_len,
                                 uint32_t sample_rate,
                                 uint8_t channels,
                                 const char *recording_id)
;

/**
 * Returns the target FPS based on the current power state.
 *
 * Flutter should use this to throttle camera frame delivery.
 * Values: 30 (Normal), 15 (Conserving), 6 (Leaf), 0 (Dormant)
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_get_target_fps(const struct PhalanxHandle *handle) ;

/**
 * Returns a JSON array of recording IDs as a C string.
 *
 * Example output: `["rec-did:key:-123456","rec-did:key:-789012"]`
 *
 * The returned string must be freed with `phalanx_free_string`.
 * Returns an empty array `"[]"` if no recordings exist.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_json` must be a valid pointer to receive the C string.
 */
 int32_t phalanx_list_recordings(struct PhalanxHandle *handle, char **out_json) ;

/**
 * Generates a `phx://` deep link URI for a recording.
 *
 * Uses the existing `PhalanxLocator` URI scheme:
 * `phx://[recording_id]#[secret]@[author_did]>[recipient_did]`
 *
 * The returned string must be freed with `phalanx_free_string`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `recipient_did` must be a valid null-terminated C string (the peer's DID).
 * * `out_link` must be a valid pointer to receive the C string.
 */

int32_t phalanx_get_share_link(const struct PhalanxHandle *handle,
                               const char *recording_id,
                               const char *recipient_did,
                               char **out_link)
;

/**
 * Opens a received `phx://` deep link — initiates recording retrieval from the mesh.
 *
 * Parses the URI, validates the recipient matches this node's DID, and triggers
 * `EgressCommand::FindProviders` to locate peers that have the recording.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `phx_link` must be a valid null-terminated C string containing a `phx://` URI.
 */
 int32_t phalanx_open_link(struct PhalanxHandle *handle, const char *phx_link) ;

/**
 * Debug-only: delete a recording without cryptographic revocation.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 */
 int32_t phalanx_debug_delete_recording(struct PhalanxHandle *handle, const char *recording_id) ;

/**
 * Debug: returns "shards=N,key=true/false" as a C string for a recording.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `out_info` must be a valid pointer to receive the C string.
 */

int32_t phalanx_debug_recording_info(struct PhalanxHandle *handle,
                                     const char *recording_id,
                                     char **out_info)
;

/**
 * Import a community membership from a serialized token (deep link payload).
 *
 * The token is a postcard-serialized `Community` struct, typically received
 * via QR code or deep link during the pre-event vouching ceremony.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `token_ptr` and `token_len` must describe a valid byte slice.
 */

int32_t phalanx_import_community(const struct PhalanxHandle *handle,
                                 const uint8_t *token_ptr,
                                 uintptr_t token_len)
;

/**
 * Set the active recording state on the MeshSentinel.
 *
 * Called by Flutter when recording starts (recording_id not null) or stops (null).
 * When active, MeshSentinel captures ProximityWitness entries and auto-seals
 * grants to the community Stronghold.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `recording_id` must be a valid null-terminated C string, or null to stop.
 */
 int32_t phalanx_set_recording_state(const struct PhalanxHandle *handle, const char *recording_id) ;

/**
 * Manually dissolve a community (panic button).
 *
 * Zeroes all membership data for the specified community. Does not affect
 * other members — each phone holds only its own credential.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `community_id_ptr` must point to exactly 32 bytes.
 */

int32_t phalanx_dissolve_community(const struct PhalanxHandle *handle,
                                   const uint8_t *community_id_ptr)
;

/**
 * Exports a recording as a C2PA-compliant MP4 with embedded forensic metadata.
 *
 * Retrieves all shards for the given recording ID from storage,
 * encodes them into H.264+AAC, muxes into MP4, and embeds a C2PA manifest:
 *   - Sensor provenance assertions (PRNU, Moiré, Laplacian) per-frame
 *   - Author DID
 *   - Recording duration, frame count
 *   - Self-signed with the node's Ed25519 key
 *
 * The output file is a standard MP4 that any C2PA validator can inspect.
 * Self-signed certificates will show as "untrusted" — that's honest.
 * The forensic data speaks for itself.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `out_path` must be a valid null-terminated C string (writable file path).
 */

int32_t phalanx_export_c2pa(const struct PhalanxHandle *handle,
                            const char *recording_id,
                            const char *out_path)
;

/**
 * Returns the file path of the last C2PA export, if any.
 * Convenience for Flutter to know where the file landed.
 *
 * The returned string must be freed with `phalanx_free_string`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `out_path` must be a valid pointer to receive the C string.
 */

int32_t phalanx_get_c2pa_export_path(const struct PhalanxHandle *handle,
                                     const char *recording_id,
                                     char **out_path)
;

/**
 * Cryptographically forget a recording. Destroys all local evidence and
 * propagates the revocation to the mesh via gossipsub and DHT.
 *
 * Requires the user's 12-word BIP39 mnemonic — the revocation private key
 * is derived from `seed[32..64]` and never stored on the device.
 *
 * Returns `PhalanxError::Ok` (0) on success, negative error code on failure.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `mnemonic_phrase` must be a valid null-terminated C string (12 BIP39 words).
 */

int32_t phalanx_forget_recording(const struct PhalanxHandle *handle,
                                 const char *recording_id,
                                 const char *mnemonic_phrase)
;

/**
 * Creates a new PhalanxHandle by bootstrapping the full engine stack.
 *
 * Mirrors `sentinel.rs` lines 24-91:
 * config → identity → vault → trust → probe → swarm → bridge → sentinel
 *
 * Returns `null` on any failure. Rust's `Drop` semantics clean up partial state.
 *
 * # Safety
 * * `config_path` must be a valid null-terminated C string, or null for defaults.
 * * `storage_path` must be a valid null-terminated C string pointing to writable storage.
 * * `passphrase` must be a valid null-terminated C string.
 */

struct PhalanxHandle *phalanx_create(const char *config_path,
                                     const char *storage_path,
                                     const char *passphrase,
                                     char **out_genesis_phrase)
;

/**
 * Starts the engine's main run loop on a background tokio task.
 *
 * Transitions: `Booting → Running`.
 * Returns `PhalanxError::AlreadyRunning` if called twice.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_start(struct PhalanxHandle *handle) ;

/**
 * Stops the engine gracefully by dropping the shutdown oneshot sender.
 *
 * Transitions: `Running → Stopped`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_stop(struct PhalanxHandle *handle) ;

/**
 * Destroys the handle and frees all resources.
 *
 * After this call, the pointer is invalid. Double-destroy is UB.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * Must be called exactly once per handle.
 * * Null is a safe no-op.
 */
 void phalanx_destroy(struct PhalanxHandle *handle) ;

/**
 * Pushes a peer discovery event from Flutter into the local mesh channel.
 *
 * Called when BLE/WiFi Direct discovers a nearby device.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `peer_id` must be a valid null-terminated C string.
 */

int32_t phalanx_local_mesh_push_peer_discovered(struct PhalanxHandle *handle,
                                                const char *peer_id)
;

/**
 * Pushes received data from a local mesh peer into the channel.
 *
 * Called when BLE/WiFi Direct receives data from a nearby device.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `peer_id` must be a valid null-terminated C string.
 * * `topic` must be a valid null-terminated C string.
 * * `data` must point to `data_len` valid bytes.
 */

int32_t phalanx_local_mesh_push_data_received(struct PhalanxHandle *handle,
                                              const char *peer_id,
                                              const char *topic,
                                              const uint8_t *data,
                                              uint32_t data_len)
;

/**
 * Pushes a peer disconnection event from Flutter into the local mesh channel.
 *
 * Called when a BLE/WiFi Direct peer goes out of range or disconnects.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `peer_id` must be a valid null-terminated C string.
 */

int32_t phalanx_local_mesh_push_peer_disconnected(struct PhalanxHandle *handle,
                                                  const char *peer_id)
;

/**
 * Polls for the next outbound local mesh packet.
 *
 * Flutter calls this to retrieve data that Rust wants to send to a local peer.
 * Returns the target peer ID, data, and data length through output parameters.
 * If no packet is available, `*out_data` is set to null and returns Ok.
 *
 * Caller must free `*out_peer` with `phalanx_free_string` and `*out_data`
 * with `phalanx_free_bytes`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_peer`, `out_data`, and `out_len` must be valid pointers.
 */

int32_t phalanx_local_mesh_poll_outbound(struct PhalanxHandle *handle,
                                         char **out_peer,
                                         uint8_t **out_data,
                                         uint32_t *out_len)
;

/**
 * Sets the local mesh transport availability flag.
 *
 * Flutter calls this when BLE/WiFi Direct becomes available or unavailable.
 * The MeshSentinel's select! loop checks `is_available()` to decide whether
 * to poll the local mesh adapter.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_local_mesh_set_available(struct PhalanxHandle *handle, bool available) ;

/**
 * Frees a null-terminated C string allocated by Rust.
 *
 * # Safety
 * * `ptr` must have been returned by a `phalanx_*` function that documents
 *   "caller must free with `phalanx_free_string`".
 * * `ptr` must not have been freed previously (double-free is UB).
 * * Passing a null pointer is a safe no-op.
 */
 void phalanx_free_string(char *ptr) ;

/**
 * Frees a byte buffer allocated by Rust.
 *
 * # Safety
 * * `ptr` must have been returned by a `phalanx_*` function that documents
 *   "caller must free with `phalanx_free_bytes`".
 * * `len` must be the exact length returned alongside the pointer.
 * * `ptr` must not have been freed previously (double-free is UB).
 * * Passing a null pointer is a safe no-op.
 */
 void phalanx_free_bytes(uint8_t *ptr, uint32_t len) ;

/**
 * Starts playback of a recording by ID. Returns an opaque PlaybackSession pointer.
 *
 * Spawns a `PlaybackCoordinator` that retrieves shards from storage,
 * decrypts them, and feeds decoded frames to internal mpsc channels.
 * Flutter polls these channels via `phalanx_poll_video_frame` / `phalanx_poll_audio_frame`.
 *
 * Returns null on failure.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 */

struct PlaybackSession *phalanx_start_playback(struct PhalanxHandle *handle,
                                               const char *recording_id)
;

/**
 * Polls for the next decoded video frame from a playback session.
 *
 * Returns the frame data through `out_data` and `out_len`.
 * If no frame is available yet, `*out_data` is set to null and returns Ok.
 * Caller must free the returned bytes with `phalanx_free_bytes`.
 *
 * # Safety
 * * `session` must be a valid pointer from `phalanx_start_playback`.
 * * `out_data` and `out_len` must be valid pointers.
 */

int32_t phalanx_poll_video_frame(struct PlaybackSession *session,
                                 uint8_t **out_data,
                                 uint32_t *out_len)
;

/**
 * Polls for the next decoded audio frame from a playback session.
 *
 * Returns the audio data through `out_data` and `out_len`.
 * If no audio is available yet, `*out_data` is set to null and returns Ok.
 * Caller must free the returned bytes with `phalanx_free_bytes`.
 *
 * # Safety
 * * `session` must be a valid pointer from `phalanx_start_playback`.
 * * `out_data` and `out_len` must be valid pointers.
 */

int32_t phalanx_poll_audio_frame(struct PlaybackSession *session,
                                 uint8_t **out_data,
                                 uint32_t *out_len)
;

/**
 * Stops playback by destroying the session.
 *
 * Dropping the session closes both receivers, which signals the
 * `PlaybackCoordinator` to terminate.
 *
 * # Safety
 * * `session` must be a valid pointer from `phalanx_start_playback`.
 * * Must be called exactly once per session. Null is a safe no-op.
 */
 void phalanx_stop_playback(struct PlaybackSession *session) ;

/**
 * Returns the current power state as an integer.
 *
 * Values: 0 = Normal, 1 = Conserving, 2 = Leaf, 3 = Dormant
 * Returns -1 on null pointer or error.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_get_power_state(const struct PhalanxHandle *handle) ;

/**
 * Returns whether a recording is currently active.
 *
 * Returns: 1 = recording, 0 = not recording, negative = error
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_is_recording(const struct PhalanxHandle *handle) ;

/**
 * Returns the node's DID (Decentralized Identifier) as a C string.
 *
 * The returned string must be freed with `phalanx_free_string`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out` must be a valid pointer to a `*mut c_char` that will receive the result.
 */
 int32_t phalanx_get_node_did(const struct PhalanxHandle *handle, char **out) ;

/**
 * Updates battery level and charging state.
 *
 * Called by Flutter every ~10 seconds via `battery_plus` package.
 * Drives the homeostatic integrals for power-state-aware duty cycling.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_update_battery(struct PhalanxHandle *handle, uint8_t level, bool charging) ;

/**
 * Updates thermal reading in degrees Celsius.
 *
 * Called by Flutter every ~10 seconds.
 * Thermal state drives power conservation transitions.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_update_thermal(struct PhalanxHandle *handle, int32_t celsius) ;

/**
 * Updates foreground/background lifecycle state.
 *
 * Called by Flutter's `WidgetsBindingObserver` on lifecycle transitions.
 * `is_foreground = true` → Normal power state.
 * `is_foreground = false` → Dormant power state (no capture on iOS).
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_update_lifecycle(struct PhalanxHandle *handle, bool is_foreground) ;

/**
 * Returns the peer list as a JSON array string.
 *
 * The returned string must be freed with `phalanx_free_string`.
 * Format: `[{"did":"did:key:...","pet_name":"Alice","level":"Verified","score":100,"is_blacklisted":false}, ...]`
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_json` must be a valid pointer to receive the C string.
 */

int32_t phalanx_get_peers(const struct PhalanxHandle *handle,
                          char **out_json)
;

/**
 * Sets the trust level for a peer.
 *
 * Trust levels: 0 = Blocked, 1 = Ignored, 2 = Verified, 3 = Ally
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `did` must be a valid null-terminated C string.
 */
 int32_t phalanx_set_trust_level(struct PhalanxHandle *handle, const char *did, int32_t level) ;

/**
 * Assigns a pet name to a peer.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `did` and `name` must be valid null-terminated C strings.
 */
 int32_t phalanx_assign_pet_name(struct PhalanxHandle *handle, const char *did, const char *name) ;

/**
 * Removes a peer from the trust registry.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `did` must be a valid null-terminated C string.
 */
 int32_t phalanx_remove_peer(struct PhalanxHandle *handle, const char *did) ;

#endif  /* PHALANX_FFI_H */
