/* Generated by cbindgen — do not edit manually. */

#ifndef PHALANX_FFI_H
#define PHALANX_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI error codes returned by all `extern "C"` functions.
 *
 * Contract: every public FFI function returns `PhalanxError as i32`.
 * The Dart wrapper maps these to typed exceptions.
 */
enum PhalanxError {
  /**
   * Operation completed successfully.
   */
  OK = 0,
  /**
   * A null pointer was passed where a valid pointer was required.
   */
  NULL_POINTER = -1,
  /**
   * The handle is in an invalid state for the requested operation.
   */
  INVALID_STATE = -2,
  /**
   * A C-string argument contained invalid UTF-8.
   */
  INVALID_UTF8 = -3,
  /**
   * Engine bootstrap failed (config, identity, vault, swarm, or sentinel).
   */
  BOOT_FAILED = -4,
  /**
   * The engine is already running; duplicate `phalanx_start` calls.
   */
  ALREADY_RUNNING = -5,
  /**
   * The engine is not running; operation requires a running engine.
   */
  NOT_RUNNING = -6,
  /**
   * An internal mpsc/oneshot channel was closed unexpectedly.
   */
  CHANNEL_CLOSED = -7,
  /**
   * A trust registry operation failed.
   */
  TRUST_ERROR = -8,
  /**
   * A playback operation failed.
   */
  PLAYBACK_ERROR = -9,
  /**
   * Configuration loading or validation failed.
   */
  CONFIG_ERROR = -10,
  /**
   * Recording is already active; duplicate `phalanx_start_recording` calls.
   */
  ALREADY_RECORDING = -11,
  /**
   * No active recording to stop or push frames to.
   */
  NOT_RECORDING = -12,
};
typedef int32_t PhalanxError;

/**
 * The opaque handle type exposed to C/Dart.
 *
 * This is the single point of contact between Rust and the outside world.
 * All fields are behind synchronization primitives suitable for concurrent
 * FFI access from arbitrary Dart isolates.
 */
typedef struct PhalanxHandle PhalanxHandle;

/**
 * Starts a new recording session.
 *
 * Generates a unique `RecordingId` and sets the handle into recording mode.
 * Returns the recording ID through `out_recording_id` (caller frees with `phalanx_free_string`).
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_recording_id` must be a valid pointer to receive the C string.
 */
 int32_t phalanx_start_recording(struct PhalanxHandle *handle, char **out_recording_id) ;

/**
 * Stops the current recording session.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_stop_recording(struct PhalanxHandle *handle) ;

/**
 * Pushes a raw Y-plane video frame through the forensic pipeline.
 *
 * Pipeline:
 * 1. `ForensicLens::analyze()` — PRNU variance, Moiré detection, Laplacian energy (256x256 center crop, 64KB, fits L1)
 * 2. `compress_frame()` — JPEG compression
 * 3. `create_video_shard()` — shard with forensic metrics
 * 4. `try_send` to video channel → `MediaEgressActor` handles mesh distribution
 *
 * Uses `try_send` — returns immediately, drops on backpressure.
 * Power-state-aware FPS is governed by Rust via `target_fps()`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `y_plane` must point to `y_len` valid bytes of raw luma data.
 * * `y_len` must equal `width * height`.
 */

int32_t phalanx_push_video_frame(struct PhalanxHandle *handle,
                                 const uint8_t *y_plane,
                                 uint32_t y_len,
                                 uint32_t width,
                                 uint32_t height,
                                 uint64_t _timestamp_ms)
;

/**
 * Returns the target FPS based on the current power state.
 *
 * Flutter should use this to throttle camera frame delivery.
 * Values: 30 (Normal), 15 (Conserving), 6 (Leaf), 0 (Dormant)
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_get_target_fps(const struct PhalanxHandle *handle) ;

/**
 * Generates a `phx://` deep link URI for a recording.
 *
 * Uses the existing `PhalanxLocator` URI scheme:
 * `phx://[recording_id]#[secret]@[author_did]>[recipient_did]`
 *
 * The returned string must be freed with `phalanx_free_string`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `recipient_did` must be a valid null-terminated C string (the peer's DID).
 * * `out_link` must be a valid pointer to receive the C string.
 */

int32_t phalanx_get_share_link(const struct PhalanxHandle *handle,
                               const char *recording_id,
                               const char *recipient_did,
                               char **out_link)
;

/**
 * Opens a received `phx://` deep link — initiates recording retrieval from the mesh.
 *
 * Parses the URI, validates the recipient matches this node's DID, and triggers
 * `EgressCommand::FindProviders` to locate peers that have the recording.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `phx_link` must be a valid null-terminated C string containing a `phx://` URI.
 */
 int32_t phalanx_open_link(struct PhalanxHandle *handle, const char *phx_link) ;

/**
 * Creates a new PhalanxHandle by bootstrapping the full engine stack.
 *
 * Mirrors `sentinel.rs` lines 24-91:
 * config → identity → vault → trust → probe → swarm → bridge → sentinel
 *
 * Returns `null` on any failure. Rust's `Drop` semantics clean up partial state.
 *
 * # Safety
 * * `config_path` must be a valid null-terminated C string, or null for defaults.
 * * `storage_path` must be a valid null-terminated C string pointing to writable storage.
 * * `passphrase` must be a valid null-terminated C string.
 */

struct PhalanxHandle *phalanx_create(const char *config_path,
                                     const char *storage_path,
                                     const char *passphrase)
;

/**
 * Starts the engine's main run loop on a background tokio task.
 *
 * Transitions: `Booting → Running`.
 * Returns `PhalanxError::AlreadyRunning` if called twice.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_start(struct PhalanxHandle *handle) ;

/**
 * Stops the engine gracefully by dropping the shutdown oneshot sender.
 *
 * Transitions: `Running → Stopped`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_stop(struct PhalanxHandle *handle) ;

/**
 * Destroys the handle and frees all resources.
 *
 * After this call, the pointer is invalid. Double-destroy is UB.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * Must be called exactly once per handle.
 * * Null is a safe no-op.
 */
 void phalanx_destroy(struct PhalanxHandle *handle) ;

/**
 * Frees a null-terminated C string allocated by Rust.
 *
 * # Safety
 * * `ptr` must have been returned by a `phalanx_*` function that documents
 *   "caller must free with `phalanx_free_string`".
 * * `ptr` must not have been freed previously (double-free is UB).
 * * Passing a null pointer is a safe no-op.
 */
 void phalanx_free_string(char *ptr) ;

/**
 * Frees a byte buffer allocated by Rust.
 *
 * # Safety
 * * `ptr` must have been returned by a `phalanx_*` function that documents
 *   "caller must free with `phalanx_free_bytes`".
 * * `len` must be the exact length returned alongside the pointer.
 * * `ptr` must not have been freed previously (double-free is UB).
 * * Passing a null pointer is a safe no-op.
 */
 void phalanx_free_bytes(uint8_t *ptr, uint32_t len) ;

/**
 * Starts playback of a recording by ID.
 *
 * Spawns a `PlaybackCoordinator` that retrieves shards from storage,
 * decrypts them, and feeds decoded frames to an internal mpsc channel.
 * Flutter polls this channel via `phalanx_poll_playback_frame`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 */
 int32_t phalanx_start_playback(struct PhalanxHandle *handle, const char *recording_id) ;

/**
 * Polls for the next decoded playback frame.
 *
 * Returns the frame data through `out_data` and `out_len`.
 * If no frame is available yet, `*out_data` is set to null and returns Ok.
 * Caller must free the returned bytes with `phalanx_free_bytes`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_data` and `out_len` must be valid pointers.
 */

int32_t phalanx_poll_playback_frame(struct PhalanxHandle *handle,
                                    uint8_t **out_data,
                                    uint32_t *out_len)
;

/**
 * Stops active playback by dropping the receiver channel.
 *
 * The `PlaybackCoordinator` will detect the closed channel and terminate.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_stop_playback(struct PhalanxHandle *handle) ;

/**
 * Returns the current power state as an integer.
 *
 * Values: 0 = Normal, 1 = Conserving, 2 = Leaf, 3 = Dormant
 * Returns -1 on null pointer or error.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_get_power_state(const struct PhalanxHandle *handle) ;

/**
 * Returns whether a recording is currently active.
 *
 * Returns: 1 = recording, 0 = not recording, negative = error
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_is_recording(const struct PhalanxHandle *handle) ;

/**
 * Returns the node's DID (Decentralized Identifier) as a C string.
 *
 * The returned string must be freed with `phalanx_free_string`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out` must be a valid pointer to a `*mut c_char` that will receive the result.
 */
 int32_t phalanx_get_node_did(const struct PhalanxHandle *handle, char **out) ;

/**
 * Updates battery level and charging state.
 *
 * Called by Flutter every ~10 seconds via `battery_plus` package.
 * Drives the homeostatic integrals for power-state-aware duty cycling.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_update_battery(struct PhalanxHandle *handle, uint8_t level, bool charging) ;

/**
 * Updates thermal reading in degrees Celsius.
 *
 * Called by Flutter every ~10 seconds.
 * Thermal state drives power conservation transitions.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_update_thermal(struct PhalanxHandle *handle, int32_t celsius) ;

/**
 * Updates foreground/background lifecycle state.
 *
 * Called by Flutter's `WidgetsBindingObserver` on lifecycle transitions.
 * `is_foreground = true` → Normal power state.
 * `is_foreground = false` → Dormant power state (no capture on iOS).
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_update_lifecycle(struct PhalanxHandle *handle, bool is_foreground) ;

/**
 * Returns the peer list as a JSON array string.
 *
 * The returned string must be freed with `phalanx_free_string`.
 * Format: `[{"did":"did:key:...","pet_name":"Alice","level":"Verified","score":100,"is_blacklisted":false}, ...]`
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_json` must be a valid pointer to receive the C string.
 */

int32_t phalanx_get_peers(const struct PhalanxHandle *handle,
                          char **out_json)
;

/**
 * Sets the trust level for a peer.
 *
 * Trust levels: 0 = Blocked, 1 = Ignored, 2 = Verified, 3 = Ally
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `did` must be a valid null-terminated C string.
 */
 int32_t phalanx_set_trust_level(struct PhalanxHandle *handle, const char *did, int32_t level) ;

/**
 * Assigns a pet name to a peer.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `did` and `name` must be valid null-terminated C strings.
 */
 int32_t phalanx_assign_pet_name(struct PhalanxHandle *handle, const char *did, const char *name) ;

/**
 * Removes a peer from the trust registry.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `did` must be a valid null-terminated C string.
 */
 int32_t phalanx_remove_peer(struct PhalanxHandle *handle, const char *did) ;

#endif  /* PHALANX_FFI_H */
