/* Generated by cbindgen — do not edit manually. */

#ifndef PHALANX_FFI_H
#define PHALANX_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Pixel format of the interleaved chroma plane from the camera.
 *
 * Android's Camera2 API delivers NV21 (VU interleaved).
 * iOS AVFoundation delivers NV12 (UV interleaved).
 * Both share the same Y plane — only the chroma byte order differs.
 */
typedef enum PixelFormat {
  /**
   * NV21: V then U interleaved. Android default.
   */
  NV21 = 0,
  /**
   * NV12: U then V interleaved. iOS default.
   */
  NV12 = 1,
} PixelFormat;

/**
 * FFI error codes returned by all `extern "C"` functions.
 *
 * Contract: every public FFI function returns `PhalanxError as i32`.
 * The Dart wrapper maps these to typed exceptions.
 */
enum PhalanxError {
  /**
   * Operation completed successfully.
   */
  OK = 0,
  /**
   * A null pointer was passed where a valid pointer was required.
   */
  NULL_POINTER = -1,
  /**
   * The handle is in an invalid state for the requested operation.
   */
  INVALID_STATE = -2,
  /**
   * A C-string argument contained invalid UTF-8.
   */
  INVALID_UTF8 = -3,
  /**
   * Engine bootstrap failed (config, identity, vault, swarm, or sentinel).
   */
  BOOT_FAILED = -4,
  /**
   * The engine is already running; duplicate `phalanx_start` calls.
   */
  ALREADY_RUNNING = -5,
  /**
   * The engine is not running; operation requires a running engine.
   */
  NOT_RUNNING = -6,
  /**
   * An internal mpsc/oneshot channel was closed unexpectedly.
   */
  CHANNEL_CLOSED = -7,
  /**
   * A trust registry operation failed.
   */
  TRUST_ERROR = -8,
  /**
   * A playback operation failed.
   */
  PLAYBACK_ERROR = -9,
  /**
   * Configuration loading or validation failed.
   */
  CONFIG_ERROR = -10,
  /**
   * Recording is already active; duplicate `phalanx_start_recording` calls.
   */
  ALREADY_RECORDING = -11,
  /**
   * No active recording to stop or push frames to.
   */
  NOT_RECORDING = -12,
  /**
   * Cryptographic Forgetting: revocation failed (bad mnemonic, key mismatch, or storage error).
   */
  REVOCATION_FAILED = -13,
  /**
   * Community ceremony failed (invalid vouch, quorum not met, expired, etc.).
   */
  CEREMONY_FAILED = -14,
  /**
   * Caller-provided output buffer was too small. `*out_len` has been
   * updated with the required size; retry with a larger buffer.
   * Part of the two-call query protocol for community query functions.
   */
  BUFFER_TOO_SMALL = -15,
  /**
   * Postcard encoding of a response payload failed. Indicates a bug in
   * the wire type, not caller error.
   */
  SERIALIZATION_FAILURE = -16,
  /**
   * Recovery walk is already in progress; duplicate `phalanx_start_recovery`
   * or attempt to start a recording / playback while recovery is mid-walk.
   * Both producer (capture) and the playback path are gated so the
   * single-tenant providers channel can't be reassigned mid-recovery.
   */
  ALREADY_RECOVERING = -17,
  /**
   * An `extern "C"` body caught a panic from inside Rust code (typically a
   * third-party crate like `c2pa` on malformed input). The panic was
   * converted to this error code by an `ffi_body!` wrapper to avoid the
   * process-abort that would otherwise occur when a panic unwinds across
   * an `extern "C"` boundary.
   */
  PANIC = -18,
  /**
   * BIP-39 mnemonic phrase failed to parse — wordlist or checksum violation.
   * Split out of `RevocationFailed` so the UI can tell the user "this phrase
   * isn't a valid BIP-39 phrase" rather than the conflated "phrase invalid
   * or recording not found."
   */
  MNEMONIC_PARSE_ERROR = -19,
  /**
   * BIP-39 phrase parsed and produced a revocation key, but that key does
   * not match the revocation key embedded in the target recording. Usually
   * means the user typed a different identity's phrase, or a typo that
   * still passes checksum.
   */
  REVOCATION_KEY_MISMATCH = -20,
  /**
   * The recording_id is not present in the local vault and no shards were
   * discoverable. Distinct from `RevocationKeyMismatch` so a recovering
   * node can tell "I don't have this yet" apart from "wrong phrase."
   */
  RECORDING_NOT_FOUND = -21,
  /**
   * `phalanx_restore` was called against a `storage_path` that already
   * contains an `identity.bin`. The caller (UI) must explicitly confirm
   * destruction of the existing on-device identity before retrying. We
   * fail closed here rather than silently overwriting — losing the on-disk
   * identity is destructive even though the mesh-side recordings are
   * untouched.
   */
  IDENTITY_ALREADY_EXISTS = -22,
  /**
   * No media encoder is available in this build. The FOSS/mobile artifact
   * compiles without the software H.264/AAC codecs and delegates on-device
   * export to a registered native platform encoder; until that backend is
   * registered (or a `software-transcode` build is used), export is
   * unsupported. Distinct code so the UI can say "export not available on
   * this build" rather than a generic failure.
   */
  NO_ENCODER = -23,
};
typedef int32_t PhalanxError;

/**
 * The opaque handle type exposed to C/Dart.
 *
 * This is the single point of contact between Rust and the outside world.
 * All fields are behind synchronization primitives suitable for concurrent
 * FFI access from arbitrary Dart isolates.
 */
typedef struct PhalanxHandle PhalanxHandle;

/**
 * Opaque playback session — owns the video + audio receivers.
 *
 * Flutter holds a `Pointer<Void>` to this. Each poll is a pure `try_recv()`
 * on the session's receiver. No Mutex. Single-owner (Flutter's main isolate).
 */
typedef struct PlaybackSession PlaybackSession;

/**
 * Sign a BLE auth challenge from a remote peer.
 *
 * Flutter calls this when it receives a BLE challenge. Rust signs with the node's
 * Ed25519 key. Flutter sends the resulting signature back over BLE.
 *
 * # Parameters
 * * `handle` — valid PhalanxHandle pointer
 * * `challenger_did_ptr/len` — the remote peer's DID (UTF-8 bytes)
 * * `nonce_ptr` — pointer to exactly 32 bytes of challenge nonce
 * * `out_signature` — pointer to 64-byte buffer for the Ed25519 signature output
 *
 * # Safety
 * All pointers must be valid. `out_signature` must point to at least 64 writable bytes.
 */

int32_t phalanx_sign_ble_challenge(const struct PhalanxHandle *handle,
                                   const uint8_t *challenger_did_ptr,
                                   uintptr_t challenger_did_len,
                                   const uint8_t *nonce_ptr,
                                   uint8_t *out_signature)
;

/**
 * Verify a BLE auth response from a remote peer.
 *
 * Flutter calls this after receiving a BLE auth response. Rust verifies the
 * Ed25519 signature. Returns 0 if verified, negative error code if not.
 *
 * # Parameters
 * * `handle` — valid PhalanxHandle pointer
 * * `responder_did_ptr/len` — the remote peer's DID (UTF-8 bytes)
 * * `our_nonce_ptr` — pointer to the 32-byte nonce we sent in our challenge
 * * `signature_ptr` — pointer to the 64-byte Ed25519 signature from the remote peer
 *
 * # Safety
 * All pointers must be valid with the specified lengths.
 */

int32_t phalanx_verify_ble_peer(const struct PhalanxHandle *handle,
                                const uint8_t *responder_did_ptr,
                                uintptr_t responder_did_len,
                                const uint8_t *our_nonce_ptr,
                                const uint8_t *signature_ptr)
;

/**
 * Starts PRNU calibration. Allocates the frame buffer.
 *
 * Call this before pushing calibration frames. Returns error if calibration
 * is already in progress.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_calibration_start(const struct PhalanxHandle *handle) ;

/**
 * Pushes a calibration frame. Runs ForensicLens on the Y-plane and stores
 * the resulting metrics.
 *
 * Call this for each calibration frame (minimum 10, maximum 100).
 * Returns error if calibration is not in progress or buffer is full.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `y_plane` must point to `y_len` valid bytes of Y-plane data.
 */

int32_t phalanx_calibration_push_frame(const struct PhalanxHandle *handle,
                                       const uint8_t *y_plane,
                                       uint32_t y_len,
                                       uint32_t width,
                                       uint32_t height)
;

/**
 * Finishes calibration, computes the PRNU floor, and writes it to `out_prnu_floor`.
 *
 * Clears the calibration buffer regardless of success/failure.
 * On success, the calibrated floor is stored — the caller (Flutter) should
 * persist it to the device config.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_prnu_floor` must be a valid pointer to receive the f32 result.
 */
 int32_t phalanx_calibration_finish(const struct PhalanxHandle *handle, float *out_prnu_floor) ;

/**
 * Starts a new recording session with default policy (publishable to mesh).
 *
 * Generates a unique `RecordingId` and sets the handle into recording mode.
 * Returns the recording ID through `out_recording_id` (caller frees with `phalanx_free_string`).
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_recording_id` must be a valid pointer to receive the C string.
 */
 int32_t phalanx_start_recording(struct PhalanxHandle *handle, char **out_recording_id) ;

/**
 * Starts a new recording session with explicit policy.
 *
 * Identical to `phalanx_start_recording` except the caller may opt the
 * recording out of mesh publication (`publishable = 0`). Recordings
 * captured with `publishable = 0` stay vault-local and are never gossipped
 * to the mesh, even after restart. Use this for sensitive captures the
 * operator wants kept on-device.
 *
 * `publishable` is treated as a boolean: `0` = local-only, any non-zero
 * value = publishable.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_recording_id` must be a valid pointer to receive the C string.
 */

int32_t phalanx_start_recording_with_options(struct PhalanxHandle *handle,
                                             int32_t publishable,
                                             char **out_recording_id)
;

/**
 * Stops the current recording session.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_stop_recording(struct PhalanxHandle *handle) ;

/**
 * Pushes a raw YUV video frame through the forensic pipeline.
 *
 * Pipeline:
 * 1. `ForensicLens::analyze()` — PRNU variance, Moiré detection, Laplacian energy (Y-plane only, 256×256 center crop, 64KB, fits L1)
 * 2. `compress_frame()` — full-color YUV→JPEG via turbojpeg (no RGB conversion)
 * 3. `create_video_shard()` — shard with forensic metrics
 * 4. `try_send` to video channel → `MediaEgressActor` handles mesh distribution
 *
 * Uses `try_send` — returns immediately, drops on backpressure.
 * Power-state-aware FPS is governed by Rust via `target_fps()`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `y_plane` must point to `y_len` valid bytes of raw luma data (`width * height`).
 * * `uv_plane` must point to `uv_len` valid bytes of interleaved chroma (`width * height / 2`).
 * * `recording_id` must be a valid null-terminated C string (returned from `phalanx_start_recording`).
 */

int32_t phalanx_push_video_frame(struct PhalanxHandle *handle,
                                 const uint8_t *y_plane,
                                 uint32_t y_len,
                                 const uint8_t *uv_plane,
                                 uint32_t uv_len,
                                 uint32_t width,
                                 uint32_t height,
                                 enum PixelFormat pixel_format,
                                 const char *recording_id,
                                 uint64_t _timestamp_ms)
;

/**
 * Pushes a raw PCM audio frame through the forensic pipeline.
 *
 * Pipeline:
 * 1. `create_audio_shard()` — wraps PCM data with LZ4 compression
 * 2. `try_send` to audio channel → `MediaEgressActor` encrypts + handles mesh distribution
 *
 * Uses `try_send` — returns immediately, drops on backpressure.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `pcm_data` must point to `pcm_len` valid bytes of 16-bit LE PCM audio.
 * * `recording_id` must be a valid null-terminated C string.
 */

int32_t phalanx_push_audio_frame(struct PhalanxHandle *handle,
                                 const uint8_t *pcm_data,
                                 uint32_t pcm_len,
                                 uint32_t sample_rate,
                                 uint8_t channels,
                                 const char *recording_id)
;

/**
 * Returns the target FPS based on the current power state.
 *
 * Flutter should use this to throttle camera frame delivery.
 * Values: 30 (Normal), 15 (Conserving), 6 (Leaf), 0 (Dormant)
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_get_target_fps(const struct PhalanxHandle *handle) ;

/**
 * Returns a JSON array of recording IDs as a C string.
 *
 * Example output: `["rec-did:key:-123456","rec-did:key:-789012"]`
 *
 * The returned string must be freed with `phalanx_free_string`.
 * Returns an empty array `"[]"` if no recordings exist.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_json` must be a valid pointer to receive the C string.
 */
 int32_t phalanx_list_recordings(struct PhalanxHandle *handle, char **out_json) ;

/**
 * Generates a `phx://` deep link URI for a recording.
 *
 * Uses the existing `PhalanxLocator` URI scheme:
 * `phx://[recording_id]#[secret]@[author_did]>[recipient_did]`
 *
 * The returned string must be freed with `phalanx_free_string`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `recipient_did` must be a valid null-terminated C string (the peer's DID).
 * * `out_link` must be a valid pointer to receive the C string.
 */

int32_t phalanx_get_share_link(const struct PhalanxHandle *handle,
                               const char *recording_id,
                               const char *recipient_did,
                               char **out_link)
;

/**
 * Opens a received `phx://` deep link — initiates recording retrieval from the mesh.
 *
 * Parses the URI, validates the recipient matches this node's DID, and triggers
 * `EgressCommand::FindProviders` to locate peers that have the recording.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `phx_link` must be a valid null-terminated C string containing a `phx://` URI.
 */
 int32_t phalanx_open_link(struct PhalanxHandle *handle, const char *phx_link) ;

/**
 * Debug-only: delete a recording without cryptographic revocation.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 */
 int32_t phalanx_debug_delete_recording(struct PhalanxHandle *handle, const char *recording_id) ;

/**
 * Hidden diagnostic (intentional — retained for field debugging, not part of
 * the production UI flow). Returns the per-recording shard count as a C string
 * in the form `"shards=N,key=true/false"`. Namespaced `phalanx_debug_*` so it
 * reads as deliberate diagnostic surface, not accidental production API.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `out_info` must be a valid pointer to receive the C string.
 */

int32_t phalanx_debug_recording_info(struct PhalanxHandle *handle,
                                     const char *recording_id,
                                     char **out_info)
;

/**
 * Compute a deterministic community fingerprint from founding parameters.
 *
 * Pure computation — no handle needed. Any device with the same inputs
 * produces the same 32-byte fingerprint.
 *
 * # Safety
 * * `name_ptr` must be a valid null-terminated C string.
 * * `dids_ptr` and `dids_len` must describe a valid postcard-serialized `Vec<String>`.
 * * `out_id` must point to a caller-allocated 32-byte buffer.
 */

int32_t phalanx_compute_community_id(const char *name_ptr,
                                     uint8_t quorum,
                                     const uint8_t *dids_ptr,
                                     uintptr_t dids_len,
                                     uint8_t *out_id)
;

/**
 * Sign a vouch for a member using this node's identity.
 *
 * Returns a Rust-allocated postcard-serialized `Vouch` that the caller
 * must free with `phalanx_free_bytes`.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `member_did_ptr` must be a valid null-terminated C string.
 * * `community_id_ptr` must point to exactly 32 bytes.
 * * `out_ptr` and `out_len` must be valid writable pointers.
 */

int32_t phalanx_sign_vouch(const struct PhalanxHandle *handle,
                           const char *member_did_ptr,
                           const uint8_t *community_id_ptr,
                           int64_t joined_at,
                           uint8_t **out_ptr,
                           uint32_t *out_len)
;

/**
 * Assemble a complete community from ceremony inputs.
 *
 * Verifies all vouch signatures, enforces quorum with dedup and
 * self-vouch exclusion, and returns a Rust-allocated postcard-serialized
 * `Community` token ready for QR distribution.
 *
 * Caller must free the output with `phalanx_free_bytes`.
 *
 * # Safety
 * * `name_ptr` must be a valid null-terminated C string.
 * * `stronghold_did_ptr` may be null (community without Stronghold).
 * * `members_ptr`/`members_len` must describe a valid postcard-serialized `Vec<CeremonyMember>`.
 * * `out_ptr` and `out_len` must be valid writable pointers.
 */

int32_t phalanx_create_community(const char *name_ptr,
                                 uint8_t quorum,
                                 int64_t joined_at,
                                 int64_t expires_at,
                                 const char *stronghold_did_ptr,
                                 const uint8_t *members_ptr,
                                 uintptr_t members_len,
                                 uint8_t **out_ptr,
                                 uint32_t *out_len)
;

/**
 * Preview a scanned `VouchRequest` for the Review screen.
 *
 * Strips the `[VOUCH_REQUEST_VERSION]` envelope, deserializes the
 * request, checks that `request.voucher_did` matches the handle's
 * DID (returning `CeremonyError::VoucherMismatch` if not), then
 * projects to a `VouchRequestPreview` that omits the voucher DID so
 * the preview type cannot be fed back into
 * [`phalanx_sign_vouch_request`] by accident.
 *
 * Pure call with respect to protocol state — no side effects, no
 * actor message, no signature produced. Safe to run on every QR
 * frame if that matches the UI.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `bytes_ptr`/`bytes_len` must describe a valid wrapped-envelope
 *   byte slice.
 * * `out_len` must be a valid writable pointer.
 * * `out_buf` may be null (sizing call) or point to `*out_len`
 *   writable bytes.
 */

int32_t phalanx_preview_vouch_request(const struct PhalanxHandle *handle,
                                      const uint8_t *bytes_ptr,
                                      uintptr_t bytes_len,
                                      uint8_t *out_buf,
                                      uintptr_t *out_len)
;

/**
 * Sign a scanned `VouchRequest` and return the wrapped `VouchResponse`.
 *
 * Strips the request envelope, decodes the `VouchRequest`, calls
 * `sign_vouch_response(&handle.keypair, &request, SystemClock.now())`
 * directly (no actor round-trip — matches `phalanx_sign_vouch`),
 * then produces a `VouchResponse` wrapped with
 * `[VOUCH_RESPONSE_VERSION]` inside the outer `Result::Ok`.
 *
 * The Dart side reads `Result<VouchResponse, CeremonyError>`, checks
 * the variant, and on `Ok(response)` serializes the wrapped bytes
 * directly to a QR / file.
 *
 * Failure modes encoded in `Result::Err`:
 * - `UnsupportedVersion { version }` — bad request envelope.
 * - `VoucherMismatch { expected, actual }` — request targets another
 *   device's DID.
 * - `ResponseStale { age_seconds }` — request is already past the
 *   freshness window.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `bytes_ptr`/`bytes_len` must describe a valid wrapped-envelope
 *   byte slice.
 * * `out_len` must be a valid writable pointer.
 * * `out_buf` may be null (sizing call) or point to `*out_len`
 *   writable bytes.
 */

int32_t phalanx_sign_vouch_request(const struct PhalanxHandle *handle,
                                   const uint8_t *bytes_ptr,
                                   uintptr_t bytes_len,
                                   uint8_t *out_buf,
                                   uintptr_t *out_len)
;

/**
 * Import a community membership from a serialized token (deep link payload).
 *
 * The token is a postcard-serialized `Community` struct, typically received
 * via QR code or deep link during the pre-event vouching ceremony.
 *
 * Returns an `ImportOutcome` (postcard-encoded) in the caller-provided output
 * buffer using the two-call protocol: first call with `out_buf = null` to
 * learn the required size, second call with an adequately sized buffer.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `token_ptr` and `token_len` must describe a valid byte slice.
 * * `out_len` must be a valid writable pointer.
 * * `out_buf` may be null (sizing call) or point to `*out_len` writable bytes.
 */

int32_t phalanx_import_community(const struct PhalanxHandle *handle,
                                 const uint8_t *token_ptr,
                                 uintptr_t token_len,
                                 uint8_t *out_buf,
                                 uintptr_t *out_len)
;

/**
 * Set the active recording state on the MeshSentinel.
 *
 * Called by Flutter when recording starts (recording_id not null) or stops (null).
 * When active, MeshSentinel captures ProximityWitness entries and auto-seals
 * grants to the community Stronghold.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `recording_id` must be a valid null-terminated C string, or null to stop.
 */
 int32_t phalanx_set_recording_state(const struct PhalanxHandle *handle, const char *recording_id) ;

/**
 * Manually dissolve a community (panic button).
 *
 * Zeroes all membership data for the specified community. Does not affect
 * other members — each phone holds only its own credential. Returns a
 * `DissolveOutcome` (postcard-encoded) in the caller-provided output
 * buffer using the two-call protocol.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `community_id_ptr` must point to exactly 32 bytes.
 * * `out_len` must be a valid writable pointer.
 * * `out_buf` may be null (sizing call) or point to `*out_len` writable bytes.
 */

int32_t phalanx_dissolve_community(const struct PhalanxHandle *handle,
                                   const uint8_t *community_id_ptr,
                                   uint8_t *out_buf,
                                   uintptr_t *out_len)
;

/**
 * List all communities currently in the TrustRegistry.
 *
 * Returns postcard-encoded `Vec<CommunitySummary>` in the output buffer
 * using the two-call protocol.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `out_len` must be a valid writable pointer.
 * * `out_buf` may be null (sizing call) or point to `*out_len` writable bytes.
 */

int32_t phalanx_list_communities(const struct PhalanxHandle *handle,
                                 uint8_t *out_buf,
                                 uintptr_t *out_len)
;

/**
 * Fetch the full roster for a single community.
 *
 * Returns postcard-encoded `Option<CommunityRoster>` — `None` if the id is
 * unknown — using the two-call protocol.
 *
 * # Safety
 * * `handle` must be a valid `PhalanxHandle` pointer.
 * * `community_id_ptr` must point to exactly 32 bytes.
 * * `out_len` must be a valid writable pointer.
 * * `out_buf` may be null (sizing call) or point to `*out_len` writable bytes.
 */

int32_t phalanx_get_community(const struct PhalanxHandle *handle,
                              const uint8_t *community_id_ptr,
                              uint8_t *out_buf,
                              uintptr_t *out_len)
;

/**
 * Preview a community token WITHOUT registering it.
 *
 * Runs the same verification pipeline as import (expiration + vouch
 * signatures) and projects the roster for the confirmation screen. Pure
 * call — no handle or registry dependency, safe to invoke before the user
 * commits to joining. Returns postcard-encoded
 * `Result<CommunityRoster, CommunityVerifyError>` using the two-call protocol.
 *
 * # Safety
 * * `token_ptr` and `token_len` must describe a valid byte slice.
 * * `out_len` must be a valid writable pointer.
 * * `out_buf` may be null (sizing call) or point to `*out_len` writable bytes.
 */

int32_t phalanx_preview_community(const uint8_t *token_ptr,
                                  uintptr_t token_len,
                                  uint64_t now_millis,
                                  uint8_t *out_buf,
                                  uintptr_t *out_len)
;

/**
 * Exports a recording as a C2PA-compliant MP4 with embedded forensic metadata.
 *
 * Retrieves all shards for the given recording ID from storage,
 * encodes them into H.264+AAC, muxes into MP4, and embeds a C2PA manifest:
 *   - Sensor provenance assertions (PRNU, Moiré, Laplacian) per-frame
 *   - Author DID
 *   - Recording duration, frame count
 *   - Self-signed with the node's Ed25519 key
 *
 * The output file is a standard MP4 that any C2PA validator can inspect.
 * Self-signed certificates will show as "untrusted" — that's honest.
 * The forensic data speaks for itself.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `out_path` must be a valid null-terminated C string (writable file path).
 */

int32_t phalanx_export_c2pa(const struct PhalanxHandle *handle,
                            const char *recording_id,
                            const char *out_path)
;

/**
 * Returns the file path of the last C2PA export, if any.
 * Convenience for Flutter to know where the file landed.
 *
 * The returned string must be freed with `phalanx_free_string`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `out_path` must be a valid pointer to receive the C string.
 */

int32_t phalanx_get_c2pa_export_path(const struct PhalanxHandle *handle,
                                     const char *recording_id,
                                     char **out_path)
;

/**
 * Cryptographically forget a recording. Destroys all local evidence and
 * propagates the revocation to the mesh via gossipsub and DHT.
 *
 * Requires the user's 12-word BIP39 mnemonic — the revocation private key
 * is derived from `seed[32..64]` and never stored on the device.
 *
 * Returns `PhalanxError::Ok` (0) on success, negative error code on failure.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 * * `mnemonic_phrase` must be a valid null-terminated C string (12 BIP39 words).
 */

int32_t phalanx_forget_recording(const struct PhalanxHandle *handle,
                                 const char *recording_id,
                                 const char *mnemonic_phrase)
;

/**
 * Creates a new PhalanxHandle by bootstrapping the full engine stack.
 *
 * Mirrors `sentinel.rs` lines 24-91:
 * config → identity → vault → trust → probe → swarm → bridge → sentinel
 *
 * Returns `null` on any failure. Rust's `Drop` semantics clean up partial state.
 *
 * # Safety
 * * `config_path` must be a valid null-terminated C string, or null for defaults.
 * * `storage_path` must be a valid null-terminated C string pointing to writable storage.
 * * `passphrase` must be a valid null-terminated C string.
 */

struct PhalanxHandle *phalanx_create(const char *config_path,
                                     const char *storage_path,
                                     const char *passphrase,
                                     char **out_genesis_phrase)
;

/**
 * Restore an identity from an existing BIP-39 mnemonic phrase and bootstrap
 * the engine. Symmetric with `phalanx_create` except the identity is derived
 * from the user-provided phrase rather than freshly generated. Fails with a
 * non-null handle only on success.
 *
 * Returns `null` on any failure. Specific error semantics:
 * - If `storage_path` already contains an `identity.bin`, fails (no handle
 *   returned). Caller must surface this to the user, confirm, delete the
 *   existing identity, and retry. We deliberately do not auto-overwrite —
 *   silently destroying an on-device identity is a destructive operation
 *   even when the BIP-39 phrase recovers the same keys.
 * - If `mnemonic_phrase` fails to parse against any of the 10 BIP-39
 *   wordlists, fails (no handle returned).
 * - Any post-identity bootstrap failure (vault, transport, etc.) also
 *   produces a null handle; partial state on disk is bounded by the
 *   transactional `save_to_disk_atomic` step.
 *
 * By design, the FFI surfaces only a null handle on failure rather than a
 * richer status code: the Flutter side calls `phalanx_validate_mnemonic`
 * first to pre-screen the phrase, leaving the remaining null causes as
 * "boot failed" from the user's perspective. This is intentional — a
 * per-cause restore-status API would be added here only if product needs
 * justify distinguishing the residual failure modes.
 *
 * # Safety
 * * `config_path` may be null (use defaults) or a valid null-terminated C
 *   string.
 * * `storage_path`, `passphrase`, and `mnemonic_phrase` must be valid
 *   null-terminated C strings.
 */

struct PhalanxHandle *phalanx_restore(const char *config_path,
                                      const char *storage_path,
                                      const char *passphrase,
                                      const char *mnemonic_phrase)
;

/**
 * Profile-aware variant of [`phalanx_create`]: select a [`DeploymentProfile`]
 * by name and optionally pair a Stronghold, instead of loading a config file.
 * This is the phone's normal create path.
 *
 * `profile_name` is a stable snake_case name (`solo_device`,
 * `community_with_stronghold`, …). `stronghold_addr` / `stronghold_did` carry
 * the Stronghold pairing, both nullable: a null `stronghold_addr` ⇒ no archival
 * peer (Solo, or an un-paired Community that boots for passive gossip); a
 * non-null address must carry a `/p2p/<peer-id>` tail or create fails loud. An
 * unknown profile or an undialable pairing yields a null handle — never a
 * silent default.
 *
 * # Safety
 * * `profile_name` must be a valid null-terminated C string.
 * * `stronghold_addr` and `stronghold_did` must each be null or a valid
 *   null-terminated C string.
 * * `storage_path` and `passphrase` must be valid null-terminated C strings.
 * * `out_genesis_phrase` must be null or a valid writable `*mut *mut c_char`.
 */

struct PhalanxHandle *phalanx_create_with_profile(const char *profile_name,
                                                  const char *stronghold_addr,
                                                  const char *stronghold_did,
                                                  const char *storage_path,
                                                  const char *passphrase,
                                                  char **out_genesis_phrase)
;

/**
 * Profile-aware variant of [`phalanx_restore`]. See
 * [`phalanx_create_with_profile`] for the profile/pairing parameters and
 * [`phalanx_restore`] for the restore semantics (existing-identity guard,
 * mnemonic parsing).
 *
 * # Safety
 * Same as [`phalanx_create_with_profile`], and additionally `mnemonic_phrase`
 * must be a valid null-terminated C string.
 */

struct PhalanxHandle *phalanx_restore_with_profile(const char *profile_name,
                                                   const char *stronghold_addr,
                                                   const char *stronghold_did,
                                                   const char *storage_path,
                                                   const char *passphrase,
                                                   const char *mnemonic_phrase)
;

/**
 * Starts the engine's main run loop on a background tokio task.
 *
 * Transitions: `Booting → Running`. Consumes the `UnspawnedEngine` stored
 * in `HandleState::Booting` by `mem::replace`-ing the variant and calling
 * `unspawned.spawn(&runtime)`. The returned `EngineLifecycle` is stored
 * in the new `HandleState::Running` variant; `phalanx_stop` consumes it.
 * The companion `EngineHandle` is discarded — the FFI's flat channel
 * fields already carry equivalent clones from bootstrap time.
 *
 * Returns `PhalanxError::AlreadyRunning` if called twice.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_start(struct PhalanxHandle *handle) ;

/**
 * Stops the engine gracefully by consuming the `EngineLifecycle` and
 * awaiting its bounded-deadline shutdown.
 *
 * Transitions: `Running → Stopped`. The lifecycle's `shutdown(self, …)`
 * signature enforces single-shot semantics at the type level; the
 * borrow checker forbids calling it twice.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_stop(struct PhalanxHandle *handle) ;

/**
 * Destroys the handle and frees all resources.
 *
 * If the engine is still `Running`, first invokes the equivalent of
 * `phalanx_stop` so the run-loop task drains within its 10-second
 * deadline. Skipping that drain (the old destroy-without-stop path)
 * would cancel in-flight shard writes when the runtime drops. Subsumes
 * audit finding M2 — the safe path is now the default, not opt-in.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * Must be called exactly once per handle.
 * * Null is a safe no-op.
 */
 void phalanx_destroy(struct PhalanxHandle *handle) ;

/**
 * Pushes a peer discovery event from Flutter into the local mesh channel.
 *
 * Called when BLE/WiFi Direct discovers a nearby device.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `peer_id` must be a valid null-terminated C string.
 */

int32_t phalanx_local_mesh_push_peer_discovered(struct PhalanxHandle *handle,
                                                const char *peer_id)
;

/**
 * Pushes received data from a local mesh peer into the channel.
 *
 * Called when BLE/WiFi Direct receives data from a nearby device.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `peer_id` must be a valid null-terminated C string.
 * * `topic` must be a valid null-terminated C string.
 * * `data` must point to `data_len` valid bytes.
 */

int32_t phalanx_local_mesh_push_data_received(struct PhalanxHandle *handle,
                                              const char *peer_id,
                                              const char *topic,
                                              const uint8_t *data,
                                              uint32_t data_len)
;

/**
 * Pushes a peer disconnection event from Flutter into the local mesh channel.
 *
 * Called when a BLE/WiFi Direct peer goes out of range or disconnects.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `peer_id` must be a valid null-terminated C string.
 */

int32_t phalanx_local_mesh_push_peer_disconnected(struct PhalanxHandle *handle,
                                                  const char *peer_id)
;

/**
 * Polls for the next outbound local mesh packet.
 *
 * Flutter calls this to retrieve data that Rust wants to send to a local peer.
 * Returns the target peer ID, data, and data length through output parameters.
 * If no packet is available, `*out_data` is set to null and returns Ok.
 *
 * Caller must free `*out_peer` with `phalanx_free_string` and `*out_data`
 * with `phalanx_free_bytes`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_peer`, `out_data`, and `out_len` must be valid pointers.
 */

int32_t phalanx_local_mesh_poll_outbound(struct PhalanxHandle *handle,
                                         char **out_peer,
                                         uint8_t **out_data,
                                         uint32_t *out_len)
;

/**
 * Sets the local mesh transport availability flag.
 *
 * Flutter calls this when BLE/WiFi Direct becomes available or unavailable.
 * The MeshSentinel's select! loop checks `is_available()` to decide whether
 * to poll the local mesh adapter.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_local_mesh_set_available(struct PhalanxHandle *handle, bool available) ;

/**
 * Frees a null-terminated C string allocated by Rust.
 *
 * # Safety
 * * `ptr` must have been returned by a `phalanx_*` function that documents
 *   "caller must free with `phalanx_free_string`".
 * * `ptr` must not have been freed previously (double-free is UB).
 * * Passing a null pointer is a safe no-op.
 */
 void phalanx_free_string(char *ptr) ;

/**
 * Frees a byte buffer allocated by Rust.
 *
 * # Safety
 * * `ptr` must have been returned by a `phalanx_*` function that documents
 *   "caller must free with `phalanx_free_bytes`".
 * * `len` must be the exact length returned alongside the pointer.
 * * `ptr` must not have been freed previously (double-free is UB).
 * * Passing a null pointer is a safe no-op.
 */
 void phalanx_free_bytes(uint8_t *ptr, uint32_t len) ;

/**
 * Validate a BIP-39 mnemonic phrase. Checks wordlist membership AND checksum
 * against the `bip39` crate's auto-detected language (English, Japanese,
 * Korean, Spanish, Chinese-Simplified, Chinese-Traditional, French, Italian,
 * Czech, or Portuguese).
 *
 * Returns:
 * * `PhalanxError::Ok` (0) — phrase parses cleanly and the checksum is valid.
 * * `PhalanxError::NullPointer` (-1) — `phrase` is null.
 * * `PhalanxError::InvalidUtf8` (-3) — `phrase` is not valid UTF-8.
 * * `PhalanxError::MnemonicParseError` (-19) — wordlist violation or
 *   checksum failure. Distinguishing between the two is intentionally
 *   omitted from the FFI surface: the Flutter caller already knows wordlist
 *   membership per cell from its local lookup, so a -19 after all cells
 *   pass the local check is necessarily a checksum failure.
 *
 * The phrase is zeroized immediately after parsing.
 *
 * # Safety
 * * `phrase` must be a valid null-terminated C string.
 */
 int32_t phalanx_validate_mnemonic(const char *phrase) ;

/**
 * Starts playback of a recording by ID. Returns an opaque PlaybackSession pointer.
 *
 * Spawns a `PlaybackCoordinator` that retrieves shards from storage,
 * decrypts them, and feeds decoded frames to internal mpsc channels.
 * Flutter polls these channels via `phalanx_poll_video_frame` / `phalanx_poll_audio_frame`.
 *
 * Returns null on failure.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `recording_id` must be a valid null-terminated C string.
 */

struct PlaybackSession *phalanx_start_playback(struct PhalanxHandle *handle,
                                               const char *recording_id)
;

/**
 * Polls for the next decoded video frame from a playback session.
 *
 * Returns the frame data through `out_data` and `out_len`.
 * If no frame is available yet, `*out_data` is set to null and returns Ok.
 * Caller must free the returned bytes with `phalanx_free_bytes`.
 *
 * # Safety
 * * `session` must be a valid pointer from `phalanx_start_playback`.
 * * `out_data` and `out_len` must be valid pointers.
 */

int32_t phalanx_poll_video_frame(struct PlaybackSession *session,
                                 uint8_t **out_data,
                                 uint32_t *out_len)
;

/**
 * Polls for the next decoded audio frame from a playback session.
 *
 * Returns the audio data through `out_data` and `out_len`.
 * If no audio is available yet, `*out_data` is set to null and returns Ok.
 * Caller must free the returned bytes with `phalanx_free_bytes`.
 *
 * # Safety
 * * `session` must be a valid pointer from `phalanx_start_playback`.
 * * `out_data` and `out_len` must be valid pointers.
 */

int32_t phalanx_poll_audio_frame(struct PlaybackSession *session,
                                 uint8_t **out_data,
                                 uint32_t *out_len)
;

/**
 * Stops playback by destroying the session.
 *
 * Dropping the session closes both receivers, which signals the
 * `PlaybackCoordinator` to terminate.
 *
 * # Safety
 * * `session` must be a valid pointer from `phalanx_start_playback`.
 * * Must be called exactly once per session. Null is a safe no-op.
 */
 void phalanx_stop_playback(struct PlaybackSession *session) ;

/**
 * Validate a Stronghold pairing (address + optional DID) before it is handed to
 * [`phalanx_create_with_profile`](crate::handle::phalanx_create_with_profile).
 * Stateless — no engine required.
 *
 * Returns `PhalanxError::Ok` (0) iff `stronghold_addr` is a dialable multiaddr
 * carrying a `/p2p/<peer-id>` tail — the same hard check `NodeConfig::assemble`
 * enforces, so a green result here guarantees create will not reject the
 * address. A typo'd or tail-less address returns `ConfigError`, letting the UI
 * say "that address looks malformed" rather than surfacing a blank boot failure
 * later. `stronghold_did` is optional (null ⇒ custody-only push); when present
 * it must be valid UTF-8.
 *
 * # Safety
 * `stronghold_addr` must be null or a valid null-terminated C string;
 * `stronghold_did` must be null or a valid null-terminated C string.
 */
 int32_t phalanx_validate_pairing(const char *stronghold_addr, const char *stronghold_did) ;

/**
 * Capability flags for a profile name, so the Dart picker is driven by Rust
 * truth rather than a hardcoded list. Returns a non-negative bitfield for a
 * known public archetype, or a negative `PhalanxError` code (`NullPointer`,
 * `InvalidUtf8`, or `ConfigError` for an unknown name) otherwise.
 *
 * Bitfield: `bit0 (1)` = known; `bit1 (2)` = needs a Stronghold pairing;
 * `bit2 (4)` = requires a PSK (not yet supplied on mobile, so the UI disables
 * those profiles). Thus `solo_device` → 1, `community_with_stronghold` → 3,
 * `affinity_group_lan` → 5, `high_risk_cross_border` → 7.
 *
 * # Safety
 * `profile_name` must be null or a valid null-terminated C string.
 */
 int32_t phalanx_profile_flags(const char *profile_name) ;

/**
 * Start a recovery walk: locate the per-identity manifest on the mesh,
 * walk it, and pull every cataloged child recording into the local vault.
 *
 * Returns:
 * * `0` on success — the walk has been spawned. Poll
 *   `phalanx_recovery_status` to track progress.
 * * `PhalanxError::NullPointer` if `handle` is null.
 * * `PhalanxError::NotRunning` if the engine isn't running.
 * * `PhalanxError::AlreadyRecording` if a recording is currently active.
 * * `PhalanxError::AlreadyRecovering` if a previous recovery is still
 *   running.
 * * `PhalanxError::InvalidState` if the engine state is otherwise wrong.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_start_recovery(const struct PhalanxHandle *handle) ;

/**
 * Postcard-encode a snapshot of the current recovery status. Caller frees
 * the returned bytes via `phalanx_free_bytes` (same lifetime contract as
 * `phalanx_sign_vouch`).
 *
 * Returns:
 * * `0` on success — `*out_ptr` and `*out_len` describe a freshly-malloc'd
 *   postcard buffer.
 * * `PhalanxError::NullPointer` if any pointer is null.
 * * `PhalanxError::SerializationFailure` if postcard fails (indicates a
 *   bug in the wire type, not caller error).
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_ptr` and `out_len` must be writable pointers.
 */

int32_t phalanx_recovery_status(const struct PhalanxHandle *handle,
                                uint8_t **out_ptr,
                                uint32_t *out_len)
;

/**
 * Cancel an in-progress recovery walk. Idempotent: calling twice or
 * calling when no recovery is active is a no-op that returns `0`.
 *
 * The orchestrator observes the cancel on its next poll iteration
 * (within ~1s) and exits with `state = Cancelled`. Partial state on disk
 * is preserved — a subsequent `phalanx_start_recovery` resumes from
 * where this one left off.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_cancel_recovery(const struct PhalanxHandle *handle) ;

/**
 * Returns the current power state as an integer.
 *
 * Values: 0 = Normal, 1 = Conserving, 2 = Leaf, 3 = Dormant
 * Returns -1 on null pointer or error.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_get_power_state(const struct PhalanxHandle *handle) ;

/**
 * Returns whether a recording is currently active.
 *
 * Returns: 1 = recording, 0 = not recording, negative = error
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_is_recording(const struct PhalanxHandle *handle) ;

/**
 * Returns the node's DID (Decentralized Identifier) as a C string.
 *
 * The returned string must be freed with `phalanx_free_string`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out` must be a valid pointer to a `*mut c_char` that will receive the result.
 */
 int32_t phalanx_get_node_did(const struct PhalanxHandle *handle, char **out) ;

/**
 * Updates battery level and charging state.
 *
 * Called by Flutter every ~10 seconds via `battery_plus` package.
 * Drives the homeostatic integrals for power-state-aware duty cycling.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_update_battery(struct PhalanxHandle *handle, uint8_t level, bool charging) ;

/**
 * Updates thermal reading in degrees Celsius.
 *
 * Called by Flutter every ~10 seconds.
 * Thermal state drives power conservation transitions.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_update_thermal(struct PhalanxHandle *handle, int32_t celsius) ;

/**
 * Updates foreground/background lifecycle state.
 *
 * Called by Flutter's `WidgetsBindingObserver` on lifecycle transitions.
 * `is_foreground = true` → Normal power state.
 * `is_foreground = false` → Dormant power state (no capture on iOS).
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_update_lifecycle(struct PhalanxHandle *handle, bool is_foreground) ;

/**
 * Updates total device RAM in bytes.
 *
 * Called once by Flutter shortly after `phalanx_create`/`phalanx_restore`,
 * using the platform's physical-memory API. RAM sizes the homeostatic
 * memory-pressure integrals; passing 0 leaves the reference-device fallback
 * in place. Additive setter — avoids an ABI change to `phalanx_create`.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 */
 int32_t phalanx_update_device_ram(struct PhalanxHandle *handle, uint64_t total_ram_bytes) ;

/**
 * Returns the peer list as a JSON array string.
 *
 * The returned string must be freed with `phalanx_free_string`.
 * Format: `[{"did":"did:key:...","pet_name":"Alice","level":"Verified","score":100,"is_blacklisted":false}, ...]`
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `out_json` must be a valid pointer to receive the C string.
 */

int32_t phalanx_get_peers(const struct PhalanxHandle *handle,
                          char **out_json)
;

/**
 * Sets the trust level for a peer.
 *
 * Trust levels: 0 = Blocked, 1 = Ignored, 2 = Verified, 3 = Ally
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `did` must be a valid null-terminated C string.
 */
 int32_t phalanx_set_trust_level(struct PhalanxHandle *handle, const char *did, int32_t level) ;

/**
 * Assigns a pet name to a peer.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `did` and `name` must be valid null-terminated C strings.
 */
 int32_t phalanx_assign_pet_name(struct PhalanxHandle *handle, const char *did, const char *name) ;

/**
 * Removes a peer from the trust registry.
 *
 * # Safety
 * * `handle` must be a valid pointer from `phalanx_create`.
 * * `did` must be a valid null-terminated C string.
 */
 int32_t phalanx_remove_peer(struct PhalanxHandle *handle, const char *did) ;

#endif  /* PHALANX_FFI_H */
